### ISSUE TITLE
Output just simplified .glb without KHR_mesh_quantization

### ISSUE THREAD

**Issue by starhopper1** [zeux/meshoptimizer#105]
Hi,
first off all awesome work.
I wanted to know if there is a option to save .glb without the quantization.
Its a bit of a hassle with the offical loader from gltf in unity.

**Comment by zeux** [comment]
This is not currently supported. I'll need to take a look as to how easy/hard it is going to be to maintain, it's probably reasonable to add this.

**Comment by zeux** [comment]
This wasn't too bad. `-noq` disables quantization now.
