### ISSUE TITLE
gltfpack: preserve material extras

### ISSUE THREAD

**Issue by jamesdolan** [zeux/meshoptimizer#108]
Currently, gltfpack discards any "extras" attached to materials when it merges materials. It would be nice if we could optionally preserve the extras when merging and only pass the `areMaterialsEqual` test if they are equal.

**Comment by zeux** [comment]
This makes a lot of sense, I am going to look into this. Unsure if adding an option for materials is worthwhile here - could this happen unconditionally? - although an option could probably be used for other places with extras like nodes.

**Comment by jamesdolan** [comment]
Always on is fine for my use-case!
