### ISSUE TITLE
Any plans to integrate with Blender and/or FreeCAD?

### ISSUE THREAD

**Issue by dumblob** [zeux/meshoptimizer#114]
Looks like there is potential for integration with some widespread software offering mesh optimization functionality, but without all the cool tricks.

Have you considered contacting them in this matter?

**Comment by zeux** [comment]
No plans to integrate this library anywhere myself, sorry - I don't have bandwidth for this. Other projects are welcome to integrate the necessary pieces on their own.

gltfpack could be a valuable post-processor for Blender glTF exporter but it can run as a standalone tool as well - I'll leave this up to Blender glTF exporter maintainers.
