### ISSUE TITLE
gltfPack ： Error during model conversion

### ISSUE THREAD

**Issue by foreverliu** [zeux/meshoptimizer#119]
RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds

**Comment by zeux** [comment]
This issue needs more information:

- Presumably this is using gltfpack from npm?
- Can you specify the command line used in the conversion?
- Most importantly, can you attach the model file used?

**Comment by zeux** [comment]
Since there's no actionable information here I'm going to close this. Feel free to reopen and provide more information requested above (also if this is using node.js I'd need the node version).
