### ISSUE TITLE
Mesh seems to turn cards into triangles

### ISSUE THREAD

**Issue by fire** [zeux/meshoptimizer#122]
https://github.com/godot-extended-libraries/mesh_lod/issues/1#issue-595554295

Problem: LODing complicated scene. Cards turn into triangles or disappear. Is this something in my code or is it a meshoptimizer problem?

**Comment by zeux** [comment]
Not sure what quality threshold is used here, but this might be related to some known issues in the simplification algorithm.

**Comment by fire** [comment]
Here's the raw glb file. 

https://send.firefox.com/download/a0a0870435bbb091/#FVXBCt9MvsoMteYPTY87Aw

I'm trying to see if the error threshold from 1e-3f to 1e-2f changes anything.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/79194714-e3222200-7de1-11ea-80c9-21c5c725bca4.png)

![editor_screenshot_2020-04-13T235005-0800](https://user-images.githubusercontent.com/32321/79194652-c554bd00-7de1-11ea-9870-cef3545e306e.png)
![editor_screenshot_2020-04-13T235026-0800](https://user-images.githubusercontent.com/32321/79194655-c5ed5380-7de1-11ea-887a-74b671c34586.png)

**Comment by fire** [comment]
Changing the target error to 1e-4f seems to change the result.

**Comment by fire** [comment]
Sorry, I changed the original model. The merging didn't do the same as the first bug. Let me try to go back.

**Comment by fire** [comment]
I was able to isolate the error again.

https://send.firefox.com/download/3423b835f809a3a3/#fAA2IZ6cSKQLDARWABOQVg

![image](https://user-images.githubusercontent.com/32321/79195778-b4a54680-7de3-11ea-96eb-653416896c99.png)

![image](https://user-images.githubusercontent.com/32321/79195792-be2eae80-7de3-11ea-9e24-414a77927731.png)

**Comment by fire** [comment]
@zeux Any ideas? I was looking into the code that determines when a index is a border or a an loop and got lost.

**Comment by zeux** [comment]
This looks similar to some issues that I have on my TODO list that have to do with border classification, where for some topological situations a geometric border isn't correctly tracking the errors.

It would help if you attach a .zip file to the issue just in case the firefox.com link goes stale. I won't be able to look into this in the next few days, unsure how long the data persists for.

**Comment by fire** [comment]
I'll upload it here. https://drive.google.com/open?id=1KpjSBHYI-bzKLba5mWDYI0QG2MpC8d6x

**Comment by fire** [comment]
Ah, thanks for your time. Hopefully, you can find some bandwidth to work on it.

**Comment by fire** [comment]
Can you take a look at this for a few hours?

**Comment by zeux** [comment]
As a matter of fact I've looked into this a bit last week and a bit this week. E.g. https://github.com/zeux/meshoptimizer/commit/fce1b277720e67be7f582b0f311d1b3cfd055aa3 was motivated by that problem.

If you want a quick and simple fix, you can change `fillEdgeQuadrics` here:

```
			// check that i0 and i1 are border/seam and are on the same edge loop
			// loop[] tracks half edges so we only need to check i0->i1
			if (k0 != k1 || (k0 != Kind_Border && k0 != Kind_Seam) || loop[i0] != i1)
				continue;
```

To do this:

```
			// check that i0 and i1 are border/seam and are on the same edge loop
			// loop[] tracks half edges so we only need to check i0->i1
			if ((k0 == Kind_Locked || k1 == Kind_Locked) && (k0 == Kind_Border || k1 == Kind_Border))
				; // hack: keep computing border errors for locked-border without a loop[] check
			else if (k0 != k1 || (k0 != Kind_Border && k0 != Kind_Seam) || loop[i0] != i1)
				continue;
```

This is not a perfect solution which is why there's no fix for this yet; I need to make a better more correct & robust fixed for border classification & filtering here.

**Comment by fire** [comment]
Wow, thanks for your help! I will play with the solution. Will report back.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/82175092-ba30f900-9887-11ea-8e55-7af971ad9a95.png)

It's looking better. It's late, so another time. Thank you again.
