### ISSUE TITLE
conver to new model, index or normal may be error

### ISSUE THREAD

**Issue by veyvin** [zeux/meshoptimizer#135]
[dc386067-d05e-4ee4-8c28-55d0b8aa94e9.mod.zip](https://github.com/zeux/meshoptimizer/files/4507210/dc386067-d05e-4ee4-8c28-55d0b8aa94e9.mod.zip)

**Comment by veyvin** [comment]
.\gltfpack.exe -noq -ke -i D:\M333\test111\MOD\dc386067-d05e-4ee4-8c28-55d0b8aa94e9.mod.glb -o D:\M333\test111\MOD\dc386067-d05e-4ee4-8c28-55d0b8aa94e922.mod.glb

**Comment by zeux** [comment]
Thanks, I can reproduce the problem - the mesh looks inverted after conversion. Will take a look.

**Comment by zeux** [comment]
Ah - yeah - the scale is negative for the mesh here, and gltfpack neglects to flip the winding on the triangles after transforming it to world space :( A temporary workaround is to use `-kn` which will disable world space transformation among other things. I'm going to fix this later today.
