### ISSUE TITLE
how to set BASISU_PATH?

### ISSUE THREAD

**Issue by karanganesan** [zeux/meshoptimizer#137]
```
Error: basisu is not present in PATH or BASISU_PATH is not set
```

this is the folder structure
<img width="299" alt="Screenshot 2020-04-22 at 7 47 16 PM" src="https://user-images.githubusercontent.com/6049925/79993164-147daa80-84d2-11ea-9343-08d4081834fa.png">

this is the env file
<img width="523" alt="Screenshot 2020-04-22 at 7 47 58 PM" src="https://user-images.githubusercontent.com/6049925/79993235-2c552e80-84d2-11ea-8829-0d551ccadccf.png">

what am I missing??? it keeps saying set PATH

**Comment by zeux** [comment]
BASISU_PATH needs to point to the executable location, so it has to contain the `basisu` file name.

**Comment by karanganesan** [comment]
yea / the executable is in the root directory as you see in the 1st image

**Comment by karanganesan** [comment]
BASISU_PATH=./basisu

is this correct?

**Comment by zeux** [comment]
`/` would commonly refer to filesystem root (so unless I'm missing something it doesn't seem right), but also right now the path variable *has to contain* the `basisu` file name, like this

```
BASISU_PATH=~/glTF-Sample-Models/basisu
```

**Comment by karanganesan** [comment]
ok I tried this 

```
BASISU_PATH=~/Users/karanganesan/Projects/Scapic/Prototypes/glTF-Sample-Models/basisu
```

this is the entire path from filesystem root 

still it's saying the same error

**Comment by zeux** [comment]
The other thing you should make sure of is that you can launch this executable with `-version` command; I believe this requires a relatively recent basisu executable.

**Comment by cristobalbahe** [comment]
Hi! I am trying to use gltfpack on windows 10 and have the same problem! 
The entry on my Path environment variable points to the bin where the basisu.exe is found.
If I run basisu -version from my terminal I get:
```
Basis Universal GPU Texture Compressor Reference Encoder v1.12.00
Copyright (C) 2019-2020 Binomial LLC, All rights reserved
```
but still get the error basisu is not present in PATH or BASISU_PATH is not set

I've also tried to set BASISU_PATH so that when I run  $Env:BASISU_PATH from PowerShell I get the path to the basisu.exe file.

I don't know what else to do and hope you can help me here!

Thank you very much!!

**Comment by zeux** [comment]
I should probably rename this variable to something like BASISU_EXECUTABLE... It must point to the .exe file, not the bin folder.

**Comment by cristobalbahe** [comment]
The thing is the BASISU_PATH variable points to the exe file, not the bin. 
I've added the bin folder to my PATH in order to use it directly from my command line, but the BASISU_PATH does point to the .exe

**Comment by zeux** [comment]
Oh interesting - this is odd. Which gltfpack build is this, the native .exe?

**Comment by zeux** [comment]
Also, what's the full path to basisu.exe? Wondering if it has spaces or other special characters.

**Comment by cristobalbahe** [comment]
I just installed today via NPM install, so version is  0.14.

Also the full path does not have spaces nor special characters. Here it is:
C:\Users\crist\Escritorio\basis_universal-master\bin\basisu.exe

**Comment by zeux** [comment]
Ah, there might be issues with the npm build running native executables - I thought I confirmed that it works but I'm not sure I tested on Windows, and it might be the case that NPM build doesn't have access to the environment variables.

You can try using the Windows executable for now, from Releases page https://github.com/zeux/meshoptimizer/releases

**Comment by cristobalbahe** [comment]
It does work! 

Thank you so much :)

**Comment by zeux** [comment]
Yeah, there's a few odd issues with npm build running basisu, that have to do with interaction of Emscripten-built executables with node environment. I'll see if I can either fix these or at least make the error message be more precise.
