### ISSUE TITLE
Usage example for `meshopt_simplify()`

### ISSUE THREAD

**Issue by corporateshark** [zeux/meshoptimizer#15]
There is no usage example of `meshopt_simplify()`.
How to properly do compactification of vertices after simplification?

**Comment by zeux** [comment]
Yeah meshopt_simplify is still experimental so it's not really reflected in the readme - the interface might change.

You can see examples of usage in https://github.com/zeux/meshoptimizer/blob/master/demo/main.cpp#L391.

This assumes that you need *all* levels of detail; if you just want to simplify your mesh and you don't need a high-resolution version, you can call meshopt_simplify which will give you a new index buffer, and then call meshopt_optimizeVertexFetch which will compact the vertex buffer and change the index buffer to refer to just vertices that are used.
