### ISSUE TITLE
gltfpack: model origin shifted after optimization

### ISSUE THREAD

**Issue by ironvelvet** [zeux/meshoptimizer#150]
Hey, first of all, thank you so much for your work on this tool. The filesize results are really looking great right now.

My use case is as follow : I'm trying to compress models I'll be using in a real time three.js scene. I use blender to correct my models and set the gltf file up. I use the CLI gltfpack to optimize my filesize.

When I use the .gltf file straight out of blender in my ThreeJS scene, the origin I set in Blender is respected. However, after having it go through gltfpack, the origin is shifted, and looks like it's somewhere in the upperleft corner relative to the model. This happens with no options, -c option, and -cc option. Basically as soon as it goes through gltfpack.

I'm sorry I don't know more, but it might be a bug with how origins are handled? This is also happening with every model I try this on. If this is user error, I'd be more than happy to learn from my mistakes!

You can find the original GLTF file with correct origin + the one that was converted by gltfpack in that zip: https://we.tl/t-4H8zlF8exe

Thank you!

**Comment by zeux** [comment]
I looked at the model and there don't seem to be any bugs here in that the model before and after optimization renders in the exact same place in Three.JS when I load it. However, depending on how you load the model maybe this can change, e.g. if you discard the mesh node and just grab the mesh geometry and attach it somewhere in your scene, the results are likely going to be off.

Can you share more about how you load the model?

**Comment by ironvelvet** [comment]
Hey, thank you for your answer, and sorry for the delay.

You are absolutely right. I was loading that wrong. Thank you so much for the insight. For anyone stumbling upon this issue, here's the breakdown :

Some stackoverflow posts advise you to load only what is considered a THREE.Mesh using ThreeJS, like so :

```
loader.load(
	'models/gltf/duck/duck.gltf',
	function ( gltf ) {
		gltf.scene.traverse((node) => {
                    if (node instanceof THREE.Mesh) {
                         scene.add(node);
                    }
                })

	}
);
```

However, if you do this, you'll simply not retrieve your modified origin. Or pretty much anything else than the mesh itself. Instead, you need to do it like this :

```
loader.load(
	'models/gltf/duck/duck.gltf',
	function ( gltf ) {
		scene.add(gltf.scene);
	}
);
```

If the result is not right, you need to fiddle with Blender or any other 3D software to make sure `gltf.scene` doesn't contain unwanted stuff.

@zeux thank you so much, and sorry for that, the issue has nothing to do with your library but it's really only the way I loaded things. Have a great day!
