### ISSUE TITLE
Verbose output as Json 

### ISSUE THREAD

**Issue by arpu** [zeux/meshoptimizer#162]
for server side Job would be nice to have the verbose output as JSON

**Comment by zeux** [comment]
Verbose output is intentionally non-structured, and it can change without notice. What information from verbose output are you interested in?

**Comment by arpu** [comment]
interested in the input/output stats

input: 8 mesh primitives (122320 triangles, 228842 vertices); 8 draw calls (8 instances, 122320 triangles)
output: 4 mesh primitives (122150 triangles, 228752 vertices); 4 draw calls (4 instances, 122150 triangles)

**Comment by zeux** [comment]
glTF-Validator (https://github.com/KhronosGroup/glTF-Validator) can produce the following report as a JSON:

```
{
    "uri": "nyra.glb",
    "mimeType": "model/gltf-binary",
    "validatorVersion": "2.0.0-dev.3.0",
    "issues": {
        "numErrors": 0,
        "numWarnings": 0,
        "numInfos": 0,
        "numHints": 0,
        "messages": [],
        "truncated": false
    },
    "info": {
        "version": "2.0",
        "generator": "gltfpack 0.14",
        "extensionsUsed": [
            "KHR_mesh_quantization"
        ],
        "extensionsRequired": [
            "KHR_mesh_quantization"
        ],
        "animationCount": 0,
        "materialCount": 1,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": false,
        "hasDefaultScene": true,
        "drawCallCount": 1,
        "totalVertexCount": 15019,
        "totalTriangleCount": 27892,
        "maxUVs": 0,
        "maxInfluences": 0,
        "maxAttributes": 2
    }
}
```

So one option is to run the validator after gltfpack if this information is required... I could also add a command-line argument to output a JSON report with some of this information.

**Comment by zeux** [comment]
(I am assuming just the output information is of interest here)

**Comment by arpu** [comment]
would nice to have this as commandline argument ( validator  would need node as runtime )

**Comment by zeux** [comment]
Ok - this isn't too difficult. What's the full set of data that you need for server-side processing?

**Comment by arpu** [comment]
this is good! maybe a commandline flag -stats  if its not to difficult than all  stats gltfpack provide
