### ISSUE TITLE
IndexAdapter breaks with Signed indices

### ISSUE THREAD

**Issue by hugoam** [zeux/meshoptimizer#174]
Hello !
I know this is probably a stupid use case, but the code I'm working with does store indices as signed integer, and IndexAdapter seems broken when given such a type of indice
This seems due to
```
template <typename T, bool ZeroCopy = sizeof(T) == sizeof(unsigned int)>
struct meshopt_IndexAdapter;
```
`unsigned int` does have the same size as `int`, so the adapter does not perform a copy here
The assumption that the size being equals means the types are the same seems dangerous there
Is this something you would be willing to fix, or is this too obscure of a use case ? 😄 

Edit: Sorry, I might have been wrong here, I'm trying to debug an issue where I get some seemingly corrupt index value, but that doesn't seem to be the issue after all... I'll investigate, but this might need to be closed

**Comment by zeux** [comment]
I believe it's correct to skip the copy here - negative values are obviously not correct inputs, but that would usually be flagged by assertions in various algorithms.

**Comment by hugoam** [comment]
Yep, I misdiagnosed an issue I was having. Found the true source, sorry for the noise !
