### ISSUE TITLE
 Name of glb changed to MESH

### ISSUE THREAD

**Issue by xx0618** [zeux/meshoptimizer#182]
I found that the internal names of the 3D models compressed with GLTFPACK have been changed to MESH. How can I keep these names unchanged and keep the original names.
![微信截图_20200925131709](https://user-images.githubusercontent.com/71865768/94229194-75058d80-ff31-11ea-92b1-6883ad2715ad.png)

**Comment by zeux** [comment]
gltfpack should preserve *node* names, but not *mesh* names - it doesn't generate any names by itself, so if you see the name change this likely means that it was omitted from the output. Can you use node names instead? They should be preserved by default on a best-effort basis, and if you pass `-kn` gltfpack will preserve all of them.

**Comment by xx0618** [comment]
In the past, I used the grid name to help me identify the grid to be replaced, so that I could accurately replace the grid. But now after compression by GLTFPACK, the name becomes MESH, I have no way to change the mesh. I don't know if there is any way to accurately replace the mesh after compression.

**Comment by xx0618** [comment]
-kn I tried to keep the nodes, but the name of the grid is still changed. But I like GLTFPACK very much, its decoding speed is very fast.

**Comment by zeux** [comment]
Right, but the mesh must be attached to a node, and that node probably has a name as well? In the source glTF file you should see `mesh` objects and `node` objects; typically both would have a name, gltfpack preserves the names for nodes (and when `-kn` is specified you should be able to replace the node / objects attached to the node the same way).

The issue is that gltfpack reprocesses the scene geometry and doesn't actually keep track of the original objects, so it might be hard to just keep the names of meshes - whereas for nodes this is already taken care of.

**Comment by xx0618** [comment]
Now the names are all MESH_*, I am not sure if the node is the one I want to replace.
What I want to do is to replace a part of it in a 3D model-A, A1-is similar in shape to A, you can replace A, if the name is the same, I might replace B with A1. And A1 and B are The difference is that the entire model becomes deformed after replacement. I wonder if there is any way to achieve the function I want?

**Comment by xx0618** [comment]
The MESH can already be replaced, thank you!

> Right, but the mesh must be attached to a node, and that node probably has a name as well? In the source glTF file you should see `mesh` objects and `node` objects; typically both would have a name, gltfpack preserves the names for nodes (and when `-kn` is specified you should be able to replace the node / objects attached to the node the same way).
> 
> The issue is that gltfpack reprocesses the scene geometry and doesn't actually keep track of the original objects, so it might be hard to just keep the names of meshes - whereas for nodes this is already taken care of.

The MESH can already be replaced, thank you!

**Comment by seed93** [comment]
But this will add an empty node for each original mesh node, and the original name belongs to the empty node, and the mesh node still has a name like `Mesh_xxx`. How to avoid the empty node?

**Comment by zeux** [comment]
The empty node contains dequantization transform and as such is needed by default, however you can now use `-vpf` flag to disable that.
