### ISSUE TITLE
Process multiple scenes without merging them

### ISSUE THREAD

**Issue by Inviz** [zeux/meshoptimizer#184]
I really love gltfpack. The speed and quality of code is superb. But I wish there was a bit more control over certain aspects of it. One of them is ability to process multiple scenes. Right now gltfpack outputs a single scene. So i have to use `gltf-transform` to preprocess file to turn scenes into root nodes.

Another semi-related thing would be super lovely to support multiple input files and glue them together as different scenes. Right now i also do that with `gltf-transform`, but it all takes a lot of plumbing and hacks

**Comment by zeux** [comment]
I could add support for multiple scenes; my understanding previously has been that this is poorly supported, some discussion in https://github.com/KhronosGroup/glTF/issues/1542 and other issues on glTF repository. Having said that, I don't think it's going to be too difficult to support, although I don't know if I will be able to find good examples to test against.

Merging multiple input files is challenging though due to how some parts of gltfpack are implemented - parts of the pipeline today use the raw data from the source glTF file (via cgltf library) so the ability to process that is limited...

**Comment by zeux** [comment]
If you have an example of a model with multiple scenes that'd be great, since glTF-Sample-Models which I usually use for testing doesn't have one.

**Comment by Inviz** [comment]
Basically, blender exports multiple scenes in a very meaningful way. It's like separate "root" nodes. When there're multiple scenes, one of them is "main" (accessible as like `gltf.scene`), it is usually the ones that blender was in while exporting. I am not super sure if there's duplication in that case (i.e. if `gltf.scene` is accessible as `gltf.scenes[n]` or is it something that GLTFLoader does).

**Comment by Inviz** [comment]
Let me make you one

**Comment by zeux** [comment]
`"scene"` is just a reference to one of the scenes, there should be no duplication in glTF file

**Comment by Inviz** [comment]
[Multi-Scenes.zip](https://github.com/zeux/meshoptimizer/files/5349013/Multi-Scenes.zip)

Here's glb, gltf and blender files.

Yes, that's right. Scene is just numeric index. Just check it myself.

**Comment by Inviz** [comment]
With multi-scene setup there could be some really interesting things done. E.g. prefabs, merged files, different animation scenes, etc. Blender has very interesting (yet a bit buggy) support for creating different scenes from the same source files, that's what I use.

**Comment by Inviz** [comment]
Hmm... I only get one scene with this new code. 

[only_one_scene.zip](https://github.com/zeux/meshoptimizer/files/5364737/only_one_scene.zip)

This test file is just blender multi-scene file exported. I also tested it on output of `gltf-transform` with multiple scenes, and also get only one scene.

> "scenes":[{"nodes":[0]}],"scene":0

**Comment by Inviz** [comment]
Wonderful work! Works well!

**Comment by Inviz** [comment]
Just wanted to note again, that you are very prolific and your utility is top-class. Does what's advertised on the tin, and is extremely fast at that. On behalf of myself and others, thank you!
