### ISSUE TITLE
getting "TextEncoder is not defined" running the macos binary.

### ISSUE THREAD

**Issue by anupamdas2012** [zeux/meshoptimizer#195]
I've installed the macos binary for gltfpack. (via npm)  I am getting a TextEncoder is not defined" error when running gltfpack.

**Comment by anupamdas2012** [comment]
this problem is resolved by updating to the latest node (14.15)

**Comment by castelblends** [comment]
Hi,

I'm using 15.1 and face the same problem, any help on how to solve this would be greatly appreciated. Thanks.
