### ISSUE TITLE
Keeping extras from VRM

### ISSUE THREAD

**Issue by fire** [zeux/meshoptimizer#198]
Hello,

I have a vrm file. It's a modification of a glb file.

When I rename it to a glb, and then do .\gltfpack.exe -ke -kn -km -ke -i '.\Short Haired Girl Black Dress Less Poly 3.glb'  -o 'Short Haired Girl Black Dress Less Poly 4.glb'.

VRM importers fails to load it as a vrm.

I have tried the `-ke` option.

Any suggestions?

[Short Haired Girl Black Dress Less Poly 3.zip](https://github.com/zeux/meshoptimizer/files/5643587/Short.Haired.Girl.Black.Dress.Less.Poly.3.zip)

All Rights Reserved. Ask me if you want license details.

https://github.com/saturday06/VRM_IMPORTER_for_Blender is an blender addon for VRM.

**Comment by avaer** [comment]
It would be useful to us too if the VRM extensions were not removed during the meshopt process. 👍

**Comment by fire** [comment]
This is my attempt to patch meshoptimizer.

https://github.com/fire/meshoptimizer/pull/1

Looking for suggestions.

```
git clone https://github.com/fire/meshoptimizer.git -b vrm 
cd meshoptimizer
mkdir build
cd build
cmake -DMESHOPT_BUILD_GLTFPACK=ON ..
make
wget https://github.com/Miraikomachi/MiraikomachiVRM/raw/master/Miraikomachi.vrm
./gltfpack -si 0.1 -noq -ke -ke -i "Miraikomachi.vrm" -o "Miraikomachi Optimize.vrm"
# Open in a vrm importer.
```

**Comment by zeux** [comment]
I'm not familiar with VRM but if it's just about preserving the top-level extension node "VRM", it should be simple. The change above might be too broad though, as it would preserve some top-level extensions where extra work needs to be performed to make the content work, e.g. KHR_xmp.

My suggestion thus would be to simply detect when "VRM" is present in the extension list (regardless of input options) and, if so, output just that extension blob, using `appendJson` which performs JSON minification.

Feel free to submit a PR along these lines. I don't have a way to test this so testing suggestions would be welcome.

**Comment by fire** [comment]
```
BEFORE 7.6M AliciaSolid_vrm-0.51.vrm
AFTER 5.5M   AliciaSolid_vrm-0.51-opt.vrm
```

From https://github.com/vrm-c/UniVRM/tree/master/Tests/Models/Alicia_vrm-0.51

Using https://vrm-viewer.yukimochi.io/ importer.

![image](https://user-images.githubusercontent.com/32321/101232512-d8fdae00-3666-11eb-8528-1732cc00b01d.png)

[AliciaSolid_vrm_opt.zip](https://github.com/zeux/meshoptimizer/files/5646429/AliciaSolid_vrm_opt.zip) from 

Notes for posterity.

On https://github.com/fire/meshoptimizer/pull/1/commits/7ab13deb033508ab3a9762486e027c55104cd28f

```
./gltfpack -si 0.8 -noq -km -kn -ke -i "AliciaSolid_vrm-0.51.vrm" -o  "AliciaSolid_vrm-0.51-opt.vrm"
```

**Comment by fire** [comment]
Thanks for the review.

I can scan for the "VRM" extension. However, I noticed some problems with extras not being sent through.

1. Enable "VRM" when seen
2. Keep extras code the same.

**Comment by fire** [comment]
I slept thinking about this optimization, because Godot Engine added autolod, I don't have a requirement for this.

The pr is salvageable for all those webxr based avatar multiverses out there. @avaer

**Comment by Ry3yr** [comment]
I hope vrm support is still being worked on.

The only other "tool" https://github.com/infosia/vrmpack?tab=readme-ov-file  that was apparantly "merged into meshoptimizer" is really a drag to compile and use...

And messing with blendshapes and such is hardly a good way to downsize a .vrm.

After all there are not many good tools for vrm (pmx has dozen.. but vrm ? )
