### ISSUE TITLE
When optimizing the gltf model, use -tc to report an error

### ISSUE THREAD

**Issue by Sea-DH1** [zeux/meshoptimizer#218]
Error: toktx is not present in PATH or TOKTX_PATH is not set

Is there any configuration missing?

**Comment by zeux** [comment]
You need toktx or basisu executable. You should be able to get toktx by using the installer from https://github.com/KhronosGroup/KTX-Software/releases

**Comment by 2xAA** [comment]
After installing the KTX-Software on macOS I still had to add

`export TOKTX_PATH="/usr/local/bin/toktx"`

to my `.zshrc` file.

**Comment by dhruvadhia1** [comment]
how did you install the KTX software on mac? 

I followed these instructions but it doesnt work 

./install-gitconfig.sh
rm TODO.md lib/mainpage.md pkgdoc/pages.md tools/toktx/toktx.cc
git checkout TODO.md lib/mainpage.md pkgdoc/pages.md tools/toktx/toktx.cc

**Comment by 2xAA** [comment]
@druhvadhia1 - the link in @zeux's reply above has an installer for macOS. Download a PKG from the of the releases and install, then add toktx to your path.

**Comment by dhruvadhia1** [comment]
it worked! awesome

**Comment by dhruvadhia1** [comment]
Also how to get KTX installed on ubuntu. I am using it with Google Cloud and was thinking of compressing on server itself. Gives me the same error as first post.

**Comment by zeux** [comment]
FWIW https://github.com/zeux/meshoptimizer/pull/264 should make the setup easier, e.g. setting TOKTX_PATH will be unnecessary if toktx is installed to /usr/local/bin.
