### ISSUE TITLE
gltfpack: Way to keep existing extensions with -noq ?

### ISSUE THREAD

**Issue by nilsmoh** [zeux/meshoptimizer#227]
Is there a way to keep existing input extensions with noq ?
Our input files contain 	"extensionsUsed": ["KHR_texture_transform"],
but our next steps do not understand additional Extensions like "KHR_mesh_quantization"
Unfortunately  -noq not only doesn't add additional extensions but actively removes those present in the input.
Is there a flag I overlooked?

Thanks for your work,
Nils

**Comment by zeux** [comment]
Oh - that’s a bug; noq should not remove texture transform extension if it’s used in the materials.
