### ISSUE TITLE
force ktx2 texture y flipped

### ISSUE THREAD

**Issue by issacclee** [zeux/meshoptimizer#241]
Hi,
Currently there is no way to force gltfpack CLI to perform y flipped on basis texture before ktx2 encoding. Would it be reasonable to add such option in the future?

**Comment by zeux** [comment]
I'm not sure if `toktx` has a way to do this - it has a `--lower_left_maps_to_s0t0` option but I don't know if it simply flips the image or if it has any other side effects. `basisu` does support `-y_flip` but gltfpack right now supports both of these.

If these options work then it's easy to add a gltfpack option to do that. Out of curiosity, what context is this necessary in?

**Comment by issacclee** [comment]
Hi Zeux,
We run a modified version of playcanvas in the frontend as the primary rendering engine. I'm not that familiar with the detailed implementation of playcanvas engine, but from what I can find it seems that playcanvas engine follows the OpenGL convention of bottom left texture origin, whereas WebGL chose texture origin to be top left.
We tried to manually run toktx with --lower_left_maps_to_s0t0 option to encode texture, and it works fine when loads into playcanvas. Thanks for letting me know there is such option in toktx.

**Comment by issacclee** [comment]
So I guess I can maybe add this option at here
![image](https://user-images.githubusercontent.com/687746/107022177-08a07200-67e0-11eb-9237-a954e4a599f0.png)
and build my own gltfpack executable to make it work?

**Comment by issacclee** [comment]
so i ended up add code to here, rebuild the executable, and it works like a charm. I'll run it with our test suite(contains 120 glb files in variant condition) tomorrow and check if there's no side effect. Thanks!
![image](https://user-images.githubusercontent.com/687746/107041693-c84eed00-67fb-11eb-911a-6da203dba7c8.png)

**Comment by zeux** [comment]
You got it! If you'd like to submit a PR with this, feel free to do so - I would name the setting `-ty`; you'd need to add smth like `bool texture_flipy` to `Settings` struct, add it to `encodeBasis` and `encodeKtx` function and add the `y_flip` / `lower_left_maps_to_s0t0` command line option conditionally.

**Comment by issacclee** [comment]
Hi Zeux,
Just got back from Chinese new year vacation. I will certainly give it a try next week. Although I've never actually worked on any production level C++ project, and my C++ knowledge is extremely limited :) ...I will probably make some silly mistakes on the way
