### ISSUE TITLE
optimizeVertexCache results

### ISSUE THREAD

**Issue by attilaz** [zeux/meshoptimizer#27]
Thanks for this library ( offtopic: also thanks for the roblox graphics api stats)

I am replacing forsyth's optimizeFaces with optimizeVertexCache.

I have tested on models from https://casual-effects.com/data/.
On most of the models the acmr is the same or better with optimizeVertexCache.

But for some models like Sports Car or Road Bike the acmr is slightly larger with optimizeVertexCache. Difference is 0.01-0.04 

I just wanted to ask if this is a known difference?  I have used meshopt_analyzeVertexCache for the test.

**Comment by zeux** [comment]
This is expected. optimizeVertexCache is using the baseline algorithm from Tom Forsyth, but it differs from it in a couple of ways:

- The algorithm is guaranteed to run in linear time on arbitrary inputs (despite the title of the algorithm, the original paper/post with it is superlinear on some inputs, and different implementations vary in complexity)
- The decisions that the algorithm makes are based on a scoring function that, unlike the original post, is learned by optimizing a large mesh data set. This means that, while on average the algorithm produces better results, it's still based on heuristics that on some meshes may return slightly less optimal order for a given hardware.

**Comment by attilaz** [comment]
thanks for the answer
