### ISSUE TITLE
gltfpack strips extra information from KHR_materials_variants extension when -ke option presents

### ISSUE THREAD

**Issue by issacclee** [zeux/meshoptimizer#271]
Hi Zeux,
Thanks for the new major release, it's a life saver.
So I've being experiment with some options that I haven't tried before. 
Below is a model that I manually put down some extras in the extension array of root level that per KHR_materials_variants spec stated should be present when use such extension.
![image](https://user-images.githubusercontent.com/687746/114498131-1ba74680-9c56-11eb-8b24-6104ef6cacc3.png)

And then I ran the model with gltfpack use the following arguments.
![image](https://user-images.githubusercontent.com/687746/114498095-0df1c100-9c56-11eb-89eb-a5f554c4849f.png)

When examine the optimized output, I've noticed that the extra infomation that I put into the root level KHR_materials_variants extension array has gone. 

I was wondering if this is the expected behavior of gltfpack's -ke option? 

I've uploaded the original files in dropbox if that helps. https://www.dropbox.com/s/rr0j7dkk2nwo0b2/raw.zip?dl=0

**Comment by issacclee** [comment]
![image](https://user-images.githubusercontent.com/687746/114498629-04b52400-9c57-11eb-80c6-51bed2c0eedb.png)

this is the post optimization variants array, as you can see, extras are gone

**Comment by zeux** [comment]
> I was wondering if this is the expected behavior of gltfpack's -ke option?

So because gltfpack fully rebuilds the target glTF file, `-ke` only preserves extras that were requested before; by default extras elsewhere are going to be omitted just because there's no code to preserve them. If your use case requires storing data in variant extras it's easy enough to add.

**Comment by issacclee** [comment]
Hi Zeux,
Thanks for the reply. I've managed to add some code which preserves the extra data for variant extensions.
I''ll close now as this is an individual use case.
