### ISSUE TITLE
Outdated documentation on -tb flag?

### ISSUE THREAD

**Issue by donmccurdy** [zeux/meshoptimizer#272]
From the gltfpack readme...

> gltfpack can also compress textures using Basis Universal format, either storing .basis images directly (**-tb flag, supported by three.js**) or using KTX2 container (-tc flag, requires support for KHR_texture_basisu). 

... this doesn't sound correct to me, THREE.GLTFLoader supports only the `KHR_texture_basisu` extension (for .ktx2 container) and there is no glTF extension for the `.basis` container. Possibly that option could be removed unless something else makes use of it?

The Basis repository contains [an older example](https://github.com/BinomialLLC/basis_universal/tree/master/webgl#gltf-3d-model) showing how you might load a custom glTF extension this way, but it's purely illustrative and should probably be updated.

**Comment by zeux** [comment]
Yeah this is no longer supported.

**Comment by zeux** [comment]
To be precise, this was a documentation only issue - the option `-tb` predated specification for KHR_texture_basisu but was removed a few releases ago to converge on the KTX2 container option. Thanks for noticing!

**Comment by donmccurdy** [comment]
Sounds good, thanks!
