### ISSUE TITLE
Applying textures for a compressed model doesn't work

### ISSUE THREAD

**Issue by yaroslavnikiforov** [zeux/meshoptimizer#280]
When applying material with textures to the compressed model it doesn't work because the texture doesn't display the pattern. I compressed the model with this command: `gltfpack -i model.gltf -o model_compressed.gltf -cc`
Here is the sandbox: [codesandbox](https://codesandbox.io/s/nervous-hooks-od2ix?file=/src/index.js) (replace model.gltf with model_compressed.gltf in loader url to reproduce)
I can't use KHR_materials_variants extension. 

Duplicate of #245

**Comment by zeux** [comment]
The same solution (copying repeat & offset values) would work here if the original model in question had a texture assigned. Without a texture, the redundant UV data gets discarded during compression. If you update the model with one that uses a texture, it would be easy to change the code to make the texture swappable.

**Comment by yaroslavnikiforov** [comment]
@zeux yes this works, I replaced the model in the sandbox with the one with texture, and to apply new texture need to do this:
```
map.repeat.copy(modelMaterial.map.repeat);
map.offset.copy(modelMaterial.map.offset);
```

Great thanks!

**Comment by zeux** [comment]
Note that you may need to set `needUpdate = true` in some cases as well (I think if the material has already been used for rendering? unsure, not an expert in three.js but I seem to remember this making the difference in some cases)

**Comment by CITIZENDOT** [comment]
Thank you @yaroslavnikiforov, for this

> map.repeat.copy(modelMaterial.map.repeat);
> map.offset.copy(modelMaterial.map.offset);
