### ISSUE TITLE
Preserve node names and structure 

### ISSUE THREAD

**Issue by redhog** [zeux/meshoptimizer#284]
I use the node tree to generate a "layer list" / "legend" for a 3d model visualizing scientific (geographical, geotechnical & geophysical) data. In my client code (based on three.js), the mesh nodes can be toggled between on/half-translucent/off, and group nodes between on/off (toggling the whole group).

Unfortunately, even with `-kn`, node names are not preserved, and neither is the node hierarchy.

Is there a way to fix this / work around this?

Example structure of my nodes to illustrate :

- Sat imagery
  - Full area
  - Over data
- Geophysical volume data
- Geophysical data slices
  - Slice along road 1
  - Slice 1 perp. to road 1
  - Slice 2 perp. to road 1
 - Geotechnical (boreholes)

**Comment by zeux** [comment]
`-kn` should fully preserve the structure of named nodes. Mesh names are currently discarded - three.js doesn't strongly differentiate between the two so the difference may not be obvious. Can you share an example glTF file or a more specific example of the structure before/after, including both node and mesh names?

**Comment by redhog** [comment]
Ah... you are right. The extra nodes threw me off. But this is something I can adjust for in the client code :) Don't mind this...
