### ISSUE TITLE
release0.16 Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Yes-Jumby** [zeux/meshoptimizer#287]
mac  compile release0.16 source code in debug mode will  get this error:
[100%] Linking CXX executable gltfpack
Undefined symbols for architecture x86_64:
  "**_meshopt_simplifyDebugKind**", referenced from:
      debugSimplify(Mesh const&, Mesh&, Mesh&, float) in mesh.cpp.o
  "**_meshopt_simplifyDebugLoop**", referenced from:
      debugSimplify(Mesh const&, Mesh&, Mesh&, float) in mesh.cpp.o
  "**_meshopt_simplifyDebugLoopBack**", referenced from:
      debugSimplify(Mesh const&, Mesh&, Mesh&, float) in mesh.cpp.o
ld: symbol(s) not found for architecture x86_64

I check the code ,i only find 
extern unsigned char* **meshopt_simplifyDebugKind**;
extern unsigned int* **meshopt_simplifyDebugLoop**;
extern unsigned int* **meshopt_simplifyDebugLoopBack**;

**Comment by zeux** [comment]
This happens when gltfpack is compiled in debug mode but meshoptimizer is compiled in release mode. Is that what you're trying to do?

**Comment by Yes-Jumby** [comment]
> This happens when gltfpack is compiled in debug mode but meshoptimizer is compiled in release mode. Is that what you're trying to do?

no，gltfpack is compiled in debug mode and meshoptimizer is also in debug mode;
 when compiled in release mode,it is ok;
I just check it:)

**Comment by zeux** [comment]
Right, yeah - thanks. This is related to symbol visibility settings. I'll take a look.
