### ISSUE TITLE
gltfpack: -kn and -mi conflict

### ISSUE THREAD

**Issue by vorg** [zeux/meshoptimizer#298]
It would seem that keep names and mesh instancing don't work together as collapsing nodes into instances would cause names to be missing.

What happens?
- using `-mi` switch together with `-kn` has no effect

How to fix it?
- Removing `-kn` produces proper instances (but nodes loose their names)

What should happen?
- with both `-mi -kn` present i would expect instances to still be created within either node of generic name or props inherited from first instance node

**Comment by zeux** [comment]
That's correct and somewhat expected though. There's unfortunately no "official" way for saving instance names, and the point of `-kn` is to preserve named nodes so that the application can modify their transforms at will. As such I'm not sure how to improve this.

**Comment by vorg** [comment]
It makes sense. I also don't see solution that wouldn't complicate things. I think this issue is a sufficient documentation so closing it now.
