### ISSUE TITLE
how to close extensions KHR_texture_transform?

### ISSUE THREAD

**Issue by Yes-Jumby** [zeux/meshoptimizer#317]
![image](https://user-images.githubusercontent.com/51182133/126133581-a6ca9b83-1d9a-46cc-bac7-c1fb76ca4d86.png)

I am creating glb form memory and then compressed by meshoptimizer,after compressed , KHR_texture_transform is added.But i really donnot want this transform added,how could I close it ?
Thanks!

**Comment by zeux** [comment]
You can use `-noq` option to disable quantization which is what requires KHR_texture_transform in the first place.

**Comment by Yes-Jumby** [comment]
> You can use `-noq` option to disable quantization which is what requires KHR_texture_transform in the first place.

thanks，it is what i want;after I put -noq on;translation and scale for mesh points ,offset and scale for KHR_texture_transform all disappeared,then the file just big a little(701kb->753kb)
