### ISSUE TITLE
Issue with quantization and KHR_materials_volume

### ISSUE THREAD

**Issue by donmccurdy** [zeux/meshoptimizer#328]
Originally reported at https://github.com/mrdoob/three.js/issues/22343, but it appears that the renderers are correct and both gltfpack and gltf-transform have a similar issue in quantizing models using the `KHR_materials_volume` extension. When compressing or quantizing this example:

![129646713-e7bcbbd7-6205-49e3-919c-0baac4d6e044](https://user-images.githubusercontent.com/1848368/129664518-cdd59a2c-ba48-4d37-80cd-06d5a0ebc0f0.png)
![Screen Shot 2021-08-16 at 9 39 20 PM](https://user-images.githubusercontent.com/1848368/129664593-1feda936-e2f1-44b7-a2e1-883f0a51cbce.png)
> Left: Original. Right: gltf-transform. Below: gltfpack.

https://github.com/mrdoob/three.js/files/6996178/Archive.zip

...the boxes should all be the same color, before and after compression. Instead they get lighter (for non-normalized vertex attributes) or darker (for normalized vertex attributes) because the node's scale affects the `material.thicknessFactor` property. I believe it's necessary to apply the inverse of the node's scale to the thickness, to compensate.

**Comment by zeux** [comment]
Thanks. This is unfortunate, since this also means the presence of the volume material should block mesh merging.

**Comment by zeux** [comment]
I think there's probably still some sort of bug in three.js here - after fixing this on gltfpack side all rows now look identical in quantized and non-quantized versions *except* for the row with thickness texture:

![image](https://user-images.githubusercontent.com/1106629/129998600-22884a7c-8fbc-49c2-9f06-476a16220653.png)

Maybe the thickness texture doesn't have the UV transform applied to it? This works correctly in Babylon.JS afaict.

**Comment by zeux** [comment]
Here's a file after the fix for testing:

[attenuation-q.zip](https://github.com/zeux/meshoptimizer/files/7011362/attenuation-q.zip)

**Comment by zeux** [comment]
Yeah seeing the same problem with texture in three.js on DragonAttenuation [which is a much nicer looking test model albeit not as pedantic as the one above :D]. Since this renders correctly in Babylon I'm going to assume it's an issue with UV xform and merge the fix here.

**Comment by zeux** [comment]
three.js issue has been fixed in https://github.com/mrdoob/three.js/pull/22364

**Comment by donmccurdy** [comment]
Thank you for the quick fix and the three.js patch here!
