### ISSUE TITLE
gltf parsing error

### ISSUE THREAD

**Issue by copycd** [zeux/meshoptimizer#345]
I think what is error in extern/cgltf.h
original code is not parsing my glb file that is parsed other viewer.
then, I fixed code. and good.

`static int cgltf_parse_json_float_array(jsmntok_t const* tokens, int i, const uint8_t* json_chunk, float* out_array, int size)
{
	**// I added code
	if (size < 1 )
		return ++i;**

	CGLTF_CHECK_TOKTYPE(tokens[i], JSMN_ARRAY);
	if (tokens[i].size != size)
	{
		return CGLTF_ERROR_JSON;
	}
	++i;
	for (int j = 0; j < size; ++j)
	{
		CGLTF_CHECK_TOKTYPE(tokens[i], JSMN_PRIMITIVE);
		out_array[j] = cgltf_json_to_float(tokens + i, json_chunk);
		++i;
	}
	return i;
}`

**Comment by zeux** [comment]
Thanks. The problematic JSON snippet is:

```
{"name":"bd0075_1_batchId","componentType":5123,"count":368,"min": 0,"max":0,"type":"SCALAR","bufferView":3,"byteOffset":0},
```

Notice that min/max are scalars. This is not allowed by glTF specification. If you use glTF Validator (https://github.khronos.org/glTF-Validator/) to check this file, you'll get the following errors:

            {
                "code": "TYPE_MISMATCH",
                "message": "Type mismatch. Property value 0 is not a 'array'.",
                "severity": 0,
                "pointer": "/accessors/3/min"
            },

That's exactly what the issue is here.
