### ISSUE TITLE
encodevertexbuffer after encodefilter in JS

### ISSUE THREAD

**Issue by meijuji202** [zeux/meshoptimizer#360]
var encoder = require("./meshopt_encoder.js");
var data = new Float32Array([
    1, 0, 0, 0,
    0, -1, 0, 0,
    0.7071068, 0, 0.707168, 1,
    -0.7071068, 0, -0.707168, 1,
]);

var encoded = encoder.encodeFilterOct(data, 4, 8, 12);
var vertexBuffer= encoder.encodeVertexBuffer(
    encoded,
    data.length,
    4
);

**errors**

**Comment by zeux** [comment]
What is the error?

**Comment by meijuji202** [comment]
var encoder = require("./meshopt_encoder.js");
var decoder = require("./meshopt_decoder.js");

var data = new Float32Array([
1, 0, 0, 0,
0, -1, 0, 0,
0.7071068, 0, 0.707168, 1,
-0.7071068, 0, -0.707168, 1,
]);

var decode =  new Float32Array(data.length);
var encoded = encoder.encodeFilterOct(data, 4, 8, 12);


var vertexBuffer= encoder.encodeVertexBuffer(
encoded,
data.length,
4
);

decoder.decodeGltfBuffer(
			new Uint8Array(decode.buffer),
			data.length,
			4,
			vertexBuffer,
			"ATTRIBUTES",
			"OCTAHEDRAL"
		);

**decoder result error**

**Comment by zeux** [comment]
You need to wait for both encoder and decoder to be ready before using them; this code works for me in node.js and prints "done".

```
var encoder = require("./meshopt_encoder.js");
var decoder = require("./meshopt_decoder.js");

var data = new Float32Array([
1, 0, 0, 0,
0, -1, 0, 0,
0.7071068, 0, 0.707168, 1,
-0.7071068, 0, -0.707168, 1,
]);

Promise.all([encoder.ready, decoder.ready]).then(() => {
	var decode = new Float32Array(data.length);
	var encoded = encoder.encodeFilterOct(data, 4, 8, 12);

	var vertexBuffer= encoder.encodeVertexBuffer(
	encoded,
	data.length,
	4
	);

	decoder.decodeGltfBuffer(
		new Uint8Array(decode.buffer),
		data.length,
		4,
		vertexBuffer,
		"ATTRIBUTES",
		"OCTAHEDRAL"
	);

	console.log("done");
});
```

**Comment by meijuji202** [comment]
> 您需要等待编码器和解码器都准备就绪才能使用它们；这段代码在 node.js 中适用于我并打印“完成”。
> 
> ```
> var encoder = require("./meshopt_encoder.js");
> var decoder = require("./meshopt_decoder.js");
> 
> var data = new Float32Array([
> 1, 0, 0, 0,
> 0, -1, 0, 0,
> 0.7071068, 0, 0.707168, 1,
> -0.7071068, 0, -0.707168, 1,
> ]);
> 
> Promise.all([encoder.ready, decoder.ready]).then(() => {
> 	var decode = new Float32Array(data.length);
> 	var encoded = encoder.encodeFilterOct(data, 4, 8, 12);
> 
> 	var vertexBuffer= encoder.encodeVertexBuffer(
> 	encoded,
> 	data.length,
> 	4
> 	);
> 
> 	decoder.decodeGltfBuffer(
> 		new Uint8Array(decode.buffer),
> 		data.length,
> 		4,
> 		vertexBuffer,
> 		"ATTRIBUTES",
> 		"OCTAHEDRAL"
> 	);
> 
> 	console.log("done");
> });
> ```

**decode  != data**

**Comment by zeux** [comment]
Octahedral filter doesn't encode floating-point values; it encodes normalized values that the GPU can read directly in the vertex shader. Here's a more correct example that shows this (note that if you want to encode floating point values directly then you can remove the filter or use an exponential filter).

```
var encoder = require("./meshopt_encoder.js");
var decoder = require("./meshopt_decoder.js");

var data = new Float32Array([
1, 0, 0, 0,
0, -1, 0, 0,
0.7071068, 0, 0.707168, 1,
-0.7071068, 0, -0.707168, 1,
]);

Promise.all([encoder.ready, decoder.ready]).then(() => {
	var decode = new Int16Array(data.length);
	var encoded = encoder.encodeFilterOct(data, 4, 8, 12);

	// each input vector gets encoded as 8 bytes (4 int16)
	var vectorCount = data.length / 4;

	var vertexBuffer= encoder.encodeVertexBuffer(
	encoded,
	vectorCount,
	8
	);

	decoder.decodeGltfBuffer(
		new Uint8Array(decode.buffer),
		vectorCount,
		8,
		vertexBuffer,
		"ATTRIBUTES",
		"OCTAHEDRAL"
	);

	for (var i = 0; i < 16; ++i)
	{
		console.log("data: ", data[i], ", decoded: ", decode[i] / 32767);
	}

	console.log("done");
});
```

output:
```
data:  1 , decoded:  1
data:  0 , decoded:  0
data:  0 , decoded:  0
data:  0 , decoded:  0
data:  0 , decoded:  0
data:  -1 , decoded:  -1
data:  0 , decoded:  0
data:  0 , decoded:  0
data:  0.7071068286895752 , decoded:  0.706747642445143
data:  0 , decoded:  0
data:  0.7071679830551147 , decoded:  0.7074495681630909
data:  1 , decoded:  1
data:  -0.7071068286895752 , decoded:  -0.706747642445143
data:  0 , decoded:  0
data:  -0.7071679830551147 , decoded:  -0.7074495681630909
data:  1 , decoded:  1
done
```

**Comment by meijuji202** [comment]
> Octahedral filter doesn't encode floating-point values; it encodes normalized values that the GPU can read directly in the vertex shader. Here's a more correct example that shows this (note that if you want to encode floating point values directly then you can remove the filter or use an exponential filter).
> 
> ```
> var encoder = require("./meshopt_encoder.js");
> var decoder = require("./meshopt_decoder.js");
> 
> var data = new Float32Array([
> 1, 0, 0, 0,
> 0, -1, 0, 0,
> 0.7071068, 0, 0.707168, 1,
> -0.7071068, 0, -0.707168, 1,
> ]);
> 
> Promise.all([encoder.ready, decoder.ready]).then(() => {
> 	var decode = new Int16Array(data.length);
> 	var encoded = encoder.encodeFilterOct(data, 4, 8, 12);
> 
> 	// each input vector gets encoded as 8 bytes (4 int16)
> 	var vectorCount = data.length / 4;
> 
> 	var vertexBuffer= encoder.encodeVertexBuffer(
> 	encoded,
> 	vectorCount,
> 	8
> 	);
> 
> 	decoder.decodeGltfBuffer(
> 		new Uint8Array(decode.buffer),
> 		vectorCount,
> 		8,
> 		vertexBuffer,
> 		"ATTRIBUTES",
> 		"OCTAHEDRAL"
> 	);
> 
> 	for (var i = 0; i < 16; ++i)
> 	{
> 		console.log("data: ", data[i], ", decoded: ", decode[i] / 32767);
> 	}
> 
> 	console.log("done");
> });
> ```
> 
> output:
> 
> ```
> data:  1 , decoded:  1
> data:  0 , decoded:  0
> data:  0 , decoded:  0
> data:  0 , decoded:  0
> data:  0 , decoded:  0
> data:  -1 , decoded:  -1
> data:  0 , decoded:  0
> data:  0 , decoded:  0
> data:  0.7071068286895752 , decoded:  0.706747642445143
> data:  0 , decoded:  0
> data:  0.7071679830551147 , decoded:  0.7074495681630909
> data:  1 , decoded:  1
> data:  -0.7071068286895752 , decoded:  -0.706747642445143
> data:  0 , decoded:  0
> data:  -0.7071679830551147 , decoded:  -0.7074495681630909
> data:  1 , decoded:  1
> done
> ```


thank you
