### ISSUE TITLE
size increases after encoder

### ISSUE THREAD

**Issue by meijuji202** [zeux/meshoptimizer#361]
```
var encoder = require("./meshopt_encoder.js");
var decoder = require("./meshopt_decoder.js");

function bytes(view) {
	return new Uint8Array(view.buffer, view.byteOffset, view.byteLength);
}

var data = new Float32Array([
1, 0, 0, 0,
0, -1, 0, 0,
0.7071068, 0, 0.707168, 1,
-0.7071068, 0, -0.707168, 1,
]);

Promise.all([encoder.ready, decoder.ready]).then(() => {
	var decode = new Int16Array(data.length);
	var encoded = encoder.encodeFilterOct(data, 4, 8, 12);

	// each input vector gets encoded as 8 bytes (4 int16)
	var vectorCount = data.length / 4;

	var vertexBuffer= encoder.encodeVertexBuffer(
	encoded,
	vectorCount,
	8
	);
});
```

**vertexBuffer.length > bytes(data).length**

**Comment by zeux** [comment]
This is expected - you're encoding a very very small buffer. The codecs are designed to work on large data streams; right now the attribute codec adds up to 32 bytes of overhead in terms of various encoding metadata plus a very small number of extra bits per input byte (~1?). When you're encoding a tiny input buffer - 32 bytes in this case (which is the result of encode filter) - the extra overhead of 32 bytes + change is obviously significant.
