### ISSUE TITLE
unexpected behaviour: gltfpack writing out 0 for light intensity

### ISSUE THREAD

**Issue by samwalls-arm** [zeux/meshoptimizer#362]
Hi there,

I'm testing out meshoptimizer via `gltfpack` for an asset in Vulkan-Samples. The input glTF contains a single light with no definition for intensity, however the output file has the light defined with `"intensity": 0`.

The asset in question is [Sponza01.gltf](https://github.com/KhronosGroup/Vulkan-Samples-Assets/blob/3178cfbe4739acd0ae59f4dee72002ca267507dd/scenes/sponza/Sponza01.gltf) (only tested on this exact commit).

I'm running this command to optimise sponza:
```
gltfpack -i assets/scenes/sponza/Sponza01.gltf -o assets/scenes/sponza/Sponza01_optimised.gltf -si 1 -noq
```

The light in the input file looks like this, for reference:
```
    "extensions": {
        "KHR_lights_punctual" : {
            "lights": [
                {
                    "color": [
                        1.0,
                        1.0,
                        1.0
                    ],
                    "type": "directional"
                }
            ]
        }
    },
```

And the output's light like this:
```
"extensions":{"KHR_lights_punctual":{"lights":[{"type":"directional","intensity":0}]}}
```

The lack of a color value is fine, since the input uses the default (1.0,1.0,1.0) - however the intensity is 0, where it should be 1 or omitted in the output.

`gltfpack -v` returns `gltfpack 0.16`.

We've looked around the source code for why this might be, but didn't see anything that obvious. Any ideas why this might be?

**Comment by zeux** [comment]
This should be fixed on master; you can check using artifacts from https://github.com/zeux/meshoptimizer/actions/runs/1413006996.

**Comment by samwalls-arm** [comment]
Thanks! It's working on the current master, yes.

Do you know when this fix will reach the version on NPM?

**Comment by zeux** [comment]
gltfpack-0.17.0 was published on NPM just now, which should solve this.
