### ISSUE TITLE
Basisu texture support on etc1s compressed textures

### ISSUE THREAD

**Issue by Kredithaichen** [zeux/meshoptimizer#363]
### What I'm doing
I am trying to compress the mesh data on .glb files after running them through gltf-transform for et1s-compression using 

`gltf-transform etc1s fileName.glb fileName.etc1s.glb`

To do so I am using 

`gltfpack -i .\066-1.0.1.1.etc1s.glb -o .\066-1.0.1.1.etc1s+meshopt.glb`

through the command line. 

### What I'm expecting
I want the meshopt compression to apply after the image data has already been compressed. 

### What actually happens
The result is the error message

`Error loading .\066-1.0.1.1.etc1s.glb: file requires BasisU texture support`

According to the [Documentation](https://meshoptimizer.org/gltf/) it requires me to add basisu to my PATH. I did so, also tried the alternative way of specifying the path to the basisu.exe in a BASISU_PATH environment variable, both of them to no avail, the error remains. 

---

What am I doing wrong? How can I get the intended result (etc1s-compression on embedded textures and meshopt-compression on mesh data)? I want to achieve this using the CLI if possible.

**Comment by zeux** [comment]
Right now gltfpack doesn't support files compressed with BasisU; the documentation is for the cases where you want to produce a file with BasisU textures (via `-tc` flag), not for cases when you want to process one.

**Comment by Kredithaichen** [comment]
Okay, thank you for the swift clarification!
