### ISSUE TITLE
Decimal separator issue in gltf pack

### ISSUE THREAD

**Issue by prasad-debug** [zeux/meshoptimizer#366]
We have integrated the gltf pack to optimize the gltf file for compression and quantization.
We have observed that we are facing the issue when we change the decimal separator of the machine to comma(,) the gltf file is not handling the numeric localization.
Adding in debug mode we are able to get the proper output of GLTF file but in case of release mode we are facing issue.

componentType":5126,"count":853,"type":"VEC3",
"min":[-7,80547619,-5,77579021,-0,248065487],// here the comma(,) is observed insteaded of dot(.)
"max":[10,199213,5,72420979,21,3658981]}// here the comma(,) is observed insteaded of dot(.)

Looking forward to hear from you.
Thanks & Regards,

**Comment by zeux** [comment]
Just to double check, this is with the native build? Is the platform Linux? This can probably be fixed by doing `    setlocale(LC_ALL, "C");` in `main()` before any other code runs.

**Comment by prasad-debug** [comment]
It worked!!
Thank you for the solution.
