### ISSUE TITLE
please mention and link to EXT_meshopt_compression  

### ISSUE THREAD

**Issue by wallabyway** [zeux/meshoptimizer#368]
I was referring someone to glTFpack the other day, and noticed there was no reference to the new extension...

Can you add a reference in the glTFpack docs and on the meshOptmizier main page, some references to EXT_meshopt_compression  ?

https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_meshopt_compression/README.md

(Or maybe I missed it, and it wasn't obvious)

**Comment by zeux** [comment]
The extension is mentioned in gltfpack readme but without a link. I can mention it in the main readme as well and add a link.
