### ISSUE TITLE
input glb has same size with output glb[target to compressed by gltftool]

### ISSUE THREAD

**Issue by Yes-Jumby** [zeux/meshoptimizer#379]
gltfpack.exe -si 0.01 -i diffusion.glb -o diffusion_001.glb

here is the glb files created by blender:
https://drive.google.com/file/d/1ERDpWWDUuH7DFVDiuSA0ZCTvhA8TS8dZ

**Comment by zeux** [comment]
Could you reupload the file using 7z or zip? In general my best guess is that the simplifier gets stuck because the topology isn't simplification-friendly. Improvements are planned in this area, but you can use -sa flag in addition to -si to force the simplifier to actually simplify the object.
