### ISSUE TITLE
Possible Texture Cordinate Issue (replacing material texture with external resource)

### ISSUE THREAD

**Issue by leoleozhu** [zeux/meshoptimizer#400]
### Background

My project does the following things
 * loads a GLTF model
 * list all the materials
 * select a material and replace its texture with an external image file

Link of this project.  https://leoleozhu.github.io/gltf-material-walker/

_It's a fork of [donmccurdy/three-gltf-viewer](https://github.com/donmccurdy/three-gltf-viewer)_

#### Correct behavior

With the original GLB and DRACO encoded GLB. I can replace the material texture with an external PNG file. (models and texture image attached).

Model created by `gltf-pipeline -i cube.glb -d -o cube-draco.glb`

<img width="881" alt="image" src="https://user-images.githubusercontent.com/738445/150296687-09aa16c8-6873-4009-8271-d63cf35427c6.png">

#### Wrong behavior

But when I try with the gltfpacked one, only the upper/top pixel covers the side in the preview.

Model created by `gltfpack -i cube.glb -c -o cube-meshopt.glb`

<img width="880" alt="image" src="https://user-images.githubusercontent.com/738445/150296755-8eb28b81-7b3d-49cd-be16-2cbce8bfb730.png">

Is it a limitation of this project, or did I miss something and some parameter change could solve my problem?

Leo

[models-and-texture.zip](https://github.com/zeux/meshoptimizer/files/7903728/models-and-texture.zip)

**Comment by zeux** [comment]
When replacing textures in compressed glTF files you need to copy over scale/offset parameters from the original texture, see https://github.com/zeux/meshoptimizer/issues/280

**Comment by leoleozhu** [comment]
> When replacing textures in compressed glTF files you need to copy over scale/offset parameters from the original texture, see #280

It's already done.
```
              var map = textureLoader.load(imgData);
              map.flipY = false;
 
              if (node.map) {
                map.repeat.copy(node.map.repeat);
                map.offset.copy(node.map.offset);
              }
 
              node.map = map;
```

**Comment by leoleozhu** [comment]
The placeholder in my model is `base color`. After assigning it a `image texture`, I can successfully replace the surface.

According to this discussion post: #305 

Thanks.

**Comment by zeux** [comment]
Yeah that's correct, I assumed your material already had a texture.
