### ISSUE TITLE
draco & gltfpack -si 1

### ISSUE THREAD

**Issue by ketourneau** [zeux/meshoptimizer#409]
Hi,

We try to use gltfpack to do mesh simplification after draco compression but we got an error : 
`file requires Draco mesh compression support`.

We also tried to do simplification before draco compression but we got bad compression.

```
gltfpack -kn -si 1 -i 01_batiment_v_6.glb -o 01_batiment_v_6_optimized.glb
gltf-pipeline --draco.compressionLevel 10 -i 01_batiment_v_6_optimized.glb -o 01_batiment_v_6_compressed.glb
```

File size result with simplificiation & draco : 29,6 mo
FIle size result with only draco : 16,1 mo

Is this normal ?
Is it possible to add Draco mesh compression support to gltfpack ?

[glb file](https://blocinbloc-development-file-service-v2.s3.fr-par.scw.cloud/01_batiment_v_6.glb.zip)

**Comment by zeux** [comment]
gltfpack assumes the source glTF file is not compressed. Support for Draco is not planned - instead the recommendation is to let gltfpack compress the data using `EXT_meshopt_compression` (`-cc`).

Note that `-si 1` is a no-op, you're asking gltfpack to simplify the mesh to the same triangle count.

I'm not sure why Draco compresses gltfpack-processed files less optimally.
