### ISSUE TITLE
Unable to disable conversion to ktx2

### ISSUE THREAD

**Issue by bzztbomb** [zeux/meshoptimizer#414]
Hello!

I'm unable to disable conversion of my jpg textures to ktx2 when using gltfpack installed via npm.  I'm guessing it may have to do with the initialization of settings?  It appears that `settings.texture_ktx` must be defaulting to true.  Maybe there's a bug with that init path and compiling to WASM?  If I compile and use the native tool, things work as I would expect.  I ran into an issue compiling with WASM as a target (I'm on OSX, I'll try a Linux machine when I have a moment), so I haven't been able to create and test a patch yet.  

Thanks!

**Comment by zeux** [comment]
Converting to KTX2 should indeed be disabled by default. When I use latest gltfpack from npm, I don't see the same effect at least on Windows.
