### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by caniko** [zeux/meshoptimizer#416]
## Motivation
Run an app that needs mesh optimization in any environment that supports a browser with WASM support (almost all modern consumer hardware).

## Contribution
I might make a PR for this in the future if I can get it working. Wandering if there is any demand.

**Comment by zeux** [comment]
Parts of meshoptimizer are already compiled to Wasm and exposed through a lightweight JS interface: https://github.com/zeux/meshoptimizer/blob/master/js/README.md

This list will probably expand over time, eg simplification will be exposed in the future but first I need to finish some interface/implementation changes.
