### ISSUE TITLE
gltfpack: Future changes for texture compression

### ISSUE THREAD

**Issue by zeux** [zeux/meshoptimizer#418]
This is an announcement about the planned changes in how gltfpack approaches texture compression. These changes are potentially breaking to existing workflows, hence this issue. Feedback welcome.

## Status quo

Today gltfpack has two modes for texture compression, using the external executable, and using the internally-integrated Basis library (will ship officially in the next meshoptimizer release, available in current pre-release builds eg https://github.com/zeux/meshoptimizer/actions/runs/1781975705).
Today gltfpack also has two distribution strategies, a native build and a Wasm/JS build runnable via node.js.

Right now the native builds support both modes based on build settings, but the JS build only supports the external executable path, because Basis doesn't cleanly compile to Wasm atm using the non-Emscripten toolchain, but even if it did the lack of threading support makes texture compression non-viable in practice because it's just too slow.

## Problems

The external executable path has been a never-ending source of support and compatibility issues. There's been many bugs in path discovery because there's just too many differences between different types of builds, maintaining it in node.js is also painful, different tools have different command line settings that *change over time in backwards-incompatible ways* (eg UASTC path got broken at some point).

Frankly, it's a mess I don't really want to deal with at this point.

The external executable path in Wasm/JS builds is only usable in node.js and requires a third-party executable. When using this mode, since you must install an executable for texture compression, it feels like switching to a native gltfpack build is a viable option. Switching to a native build in this situation is *good* - you are gaining an ability to process very large .obj/.gltf files, it's easier to debug issues, the processing is faster, and there's no real difference in safety because you're running a native executable either way, so if you are dealing with untrusted input you need to sandbox this via a container *anyway*.

When using a native executable, it shouldn't really matter if you are using an external executable or a built-in compressor - or rather, an external executable is *never* better because it's slower (gltfpack parallelizes compression over multiple files more efficiently), prone to command line argument compat issues and path discovery problems, and requires you to distribute two executables.

## Plan

Thus, the plan is very simple and straightforward:

> gltfpack will stop supporting texture compression via an external executable.

What does this mean?

- For native builds, texture compression will use internal compressor at all times. For this to work, gltfpack must be compiled with bundled Basis; this is the case for builds produced on CI, and it's easy to setup yourself. gltfpack currently uses a fork of Basis with a few changes, once these all get merged it will switch to tracking a specific version of upstream Basis library.

- For node.js builds, texture compression will *not* be available. It would still be possible to use a tool like gltf-transform to post-process gltfpack-produced files if you want to run this in node, but per above it doesn't actually seem to be beneficial.

The plan is to implement these changes in the next release (0.18). This release will also feature the new integrated mode for which the preview builds are available.

For anybody using gltfpack CLI via node, it should be very straightforward to grab a native binary instead.

For people who use gltfpack via node but driving it from a separate JS script, it should be reasonably easy to execute a native gltfpack binary using `child_process` node module. This will get you faster execution and allow for processing larger files.

## Future of node.js builds?

For now, the plan is to keep maintaining gltfpack.js, just without texture compression.

There's a few different possibilities for gltfpack.js long term. It may eventually get phased out completely in favor of native builds, or it might get full support for texture compression as compilation/runtime pipelines evolve and it becomes more practical.

For now, there's no specific plan for this, and while maintaining JS counterpart isn't very pretty, it's also not too bad so we'll keep this alive.

**Comment by wmurphyrd** [comment]
>For people who use gltfpack via node but driving it from a separate JS script, it should be reasonably easy to execute a native gltfpack binary using child_process node module. This will get you faster execution and allow for processing larger files.

I have a pipeline that runs gltfpack and basis encoding entirely in the client browser via wasm builds of both projects, so for this pipeline the native gltfpack binary is not an option.

**Comment by clibequilibrium** [comment]
> > For people who use gltfpack via node but driving it from a separate JS script, it should be reasonably easy to execute a native gltfpack binary using child_process node module. This will get you faster execution and allow for processing larger files.
> 
> I have a pipeline that runs gltfpack and basis encoding entirely in the client browser via wasm builds of both projects, so for this pipeline the native gltfpack binary is not an option.

Hi sorry for necroing. Do you by chance have an example of it ? My use case is allow the client optimize their GLTF before uploading it to S3 bucket.
