### ISSUE TITLE
Preserving the heirarchy after passing -noq -kn is not working properly

### ISSUE THREAD

**Issue by AhmadMansy** [zeux/meshoptimizer#425]
i mention the issue here [424](https://github.com/zeux/meshoptimizer/issues/424). and the answer came that i have to disable quantization which is what i am already doing ( to be able to use draco compression later using gltf-transform)
but the first model that came after gltfpack is done has a wrong heirarchy (see images in the other issue)

**Comment by zeux** [comment]
Please don't file repeated issues for this, this issue provides no new information compared to the old issue and as such is unactionable.

**Comment by AhmadMansy** [comment]
sorry for that but the old one is closed
