### ISSUE TITLE
Mesh Simplify available as WASM

### ISSUE THREAD

**Issue by bhouston** [zeux/meshoptimizer#427]
Is this available as a WASM module at this time?  How much work is it to convert to a WARM module like the other components that are already realized as WASM?

(This is an amazing tool overall, just trying to make it even more accessible.)

**Comment by zeux** [comment]
This should not be very difficult, and it's planned. In fact it's easy to compile the simplifier to wasm (the provided Makefile already supports this, although it requires a rather specific toolchain setup), but I haven't written the JS wrapper in the same style as encoder/decoder. This will happen but right now I'm not fully happy with the interface that the simplifier provides, so I didn't want to expose any JS-level interfaces to something that's still in flux.
