### ISSUE TITLE
objects get their attributes reset to -1 after using gltfpack

### ISSUE THREAD

**Issue by RGdevz** [zeux/meshoptimizer#431]
I'm using gltfpack last version to optimize scenes and I have this bug(?) that some objects and spotlights get their attributes reset to -1 for some reason

to reproduce run the example [model](https://github.com/RGdevz/typeracerbot/blob/main/test.glb?raw=true) through gltfpack with any kind of arguments then observe it in [https://gltf.report/](https://gltf.report/) and see the bug, the metalness and roughness is getting set to -1

**Comment by zeux** [comment]
This model is invalid: if you run it through https://github.khronos.org/glTF-Validator/ you will see that it saves metallic/roughness factors as strings, but the glTF spec requires them to be numbers:

```
            {
                "code": "TYPE_MISMATCH",
                "message": "Type mismatch. Property value '1' is not a 'number'.",
                "severity": 0,
                "pointer": "/materials/0/pbrMetallicRoughness/metallicFactor"
            },
            {
                "code": "TYPE_MISMATCH",
                "message": "Type mismatch. Property value '0' is not a 'number'.",
                "severity": 0,
                "pointer": "/materials/0/pbrMetallicRoughness/roughnessFactor"
            },
```

**Comment by RGdevz** [comment]
Oh ok thanks for letting me know and the quick response! I'll close the issue
