### ISSUE TITLE
cmake and basisu

### ISSUE THREAD

**Issue by ZikZakFR** [zeux/meshoptimizer#437]
In the cmake file the path for basisu is empty.
I can find the binary in /usr/local/bin but still the make process will fail on missing .h file.

/meshoptimizer/gltf/basisenc.cpp:14:10: fatal error: encoder/basisu_comp.h: No such file or directory
   14 | #include "encoder/basisu_comp.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by zeux** [comment]
The CMake path should point to a source checkout of https://github.com/zeux/basis_universal/tree/gltfpack, not a binary.

**Comment by zeux** [comment]
You have to use the fork currently (gltfpack branch specifically). There's a couple changes related to multithreading that upstream doesn't have; once a few PRs get merged upstream it's going to be possible to switch to the unmodified version, but for now the fork is required.

**Comment by ZikZakFR** [comment]
> You have to use the fork currently (gltfpack branch specifically). There's a couple changes related to multithreading that upstream doesn't have; once a few PRs get merged upstream it's going to be possible to switch to the unmodified version, but for now the fork is required.

So I did, and it failed the exact same way.

**Comment by zeux** [comment]
You need to make sure to use gltfpack branch.

**Comment by ZikZakFR** [comment]
Okay, then I (and others who read this ticket) will need the details.

**Comment by zeux** [comment]
The build instructions are ran on GHA which may help in case you're doing something differently, see this:

https://github.com/zeux/meshoptimizer/blob/master/.github/workflows/release.yml#L18-L26

The "checkout" action should map to git clone <url> + git checkout gltfpack.

Note that you could also grab a ready release artifact from https://github.com/zeux/meshoptimizer/actions/runs/2684166777

**Comment by ZikZakFR** [comment]
I'm using archlinux the command listed above
cmake . -DMESHOPT_BUILD_GLTFPACK=ON -DMESHOPT_BASISU_PATH=basis_universal -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded" -DCMAKE_BUILD_TYPE=Release

I run it from a build folder within meshoptimizer although the path is then incorrect towards basis_universal

Fixing the path then the compilation still fails with:

[ 56%] Building CXX object CMakeFiles/gltfpack.dir/gltf/basisenc.cpp.o
/GIT/meshoptimizer/gltf/basisenc.cpp: In function ‘void encodeImages(std::string*, const cgltf_data*, const std::vector<ImageInfo>&, const char*, const Settings&)’:
/GIT/meshoptimizer/gltf/basisenc.cpp:159:34: error: no matching function for call to ‘basisu::job_pool::add_job(encodeImages(std::string*, const cgltf_data*, const std::vector<ImageInfo>&, const char*, const Settings&)::<lambda()>, std::nullptr_t)’
  159 |                 gJobPool->add_job([=]() {
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~
  160 |                         std::string img_data;
      |                         ~~~~~~~~~~~~~~~~~~~~~
  161 |                         std::string mime_type;
      |                         ~~~~~~~~~~~~~~~~~~~~~~
  162 |                         std::string result;
      |                         ~~~~~~~~~~~~~~~~~~~
  163 | 
      |                                   
  164 |                         if (readImage(image, input_path, img_data, mime_type) && encodeImage(img_data, mime_type.c_str(), result, info, settings))
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  165 |                         {
      |                         ~         
  166 |                                 encoded[i].swap(result);
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~
  167 |                         }
      |                         ~         
  168 |                 }, nullptr); // explicitly pass token to make sure we're using thread-safe job_pool implementation
      |                 ~~~~~~~~~~~       
In file included from /GIT/basis_universal/encoder/basisu_frontend.h:16,
                 from /GIT/basis_universal/encoder/basisu_comp.h:16,
                 from /GIT/meshoptimizer/gltf/basisenc.cpp:14:
/GIT/basis_universal/encoder/basisu_enc.h:703:22: note: candidate: ‘void basisu::job_pool::add_job(const std::function<void()>&)’
  703 |                 void add_job(const std::function<void()>& job);
      |                      ^~~~~~~
/GIT/basis_universal/encoder/basisu_enc.h:703:22: note:   candidate expects 1 argument, 2 provided
/GIT/basis_universal/encoder/basisu_enc.h:704:22: note: candidate: ‘void basisu::job_pool::add_job(std::function<void()>&&)’
  704 |                 void add_job(std::function<void()>&& job);
      |                      ^~~~~~~
/GIT/basis_universal/encoder/basisu_enc.h:704:22: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/gltfpack.dir/build.make:90: CMakeFiles/gltfpack.dir/gltf/basisenc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/gltfpack.dir/all] Error 2
make: *** [Makefile:136: all] Error 2


Note that I installed it from AUR, and also that without basis_universal it compiles flawlessly.

**Comment by zeux** [comment]
> /GIT/meshoptimizer/gltf/basisenc.cpp:159:34: error: no matching function for call to ‘basisu::job_pool::add_job(encodeImages(std::string*, const cgltf_data*, const std::vector&, const char*, const Settings&)::<lambda()>, std::nullptr_t)’

This error means that the basis_universal version you are using is *not* from gltfpack branch per instructions above. The correct definition is here:

https://github.com/zeux/basis_universal/blob/gltfpack/encoder/basisu_enc.h#L705

If the function only has one parameter, it means you're not using the gltfpack branch.

**Comment by ZikZakFR** [comment]
That's odd, considering I did a clone of https://github.com/zeux/basis_universal.git
Then the path from meshoptimizer points to it.
Is there an extra command I should use after that?

**Comment by zeux** [comment]
Yes, you need to run `git checkout gltfpack` in that folder.
