### ISSUE TITLE
Trojan:Script/Wacatac.B!ml detected in v0.18 gltfpack-windows.zip - false positive?

### ISSUE THREAD

**Issue by metareason** [zeux/meshoptimizer#448]
Hello!

Thanks for your work on gltfpack!

Just tried to download https://github.com/zeux/meshoptimizer/releases/download/v0.18/gltfpack-windows.zip and Windows 11 Windows Defender blocked it saying it contains Trojan:Script/Wacatac.B!ml

![image](https://user-images.githubusercontent.com/480747/183075965-d1bc6896-e1d6-46bd-a42a-befad2d115f8.png)

v0.17 seems to fine https://github.com/zeux/meshoptimizer/releases/download/v0.17/gltfpack-windows.zip

I also checked for other repos with this problem, seems like it could be a false positive https://github.com/search?q=Trojan%3AScript%2FWacatac.B%21ml&type=issues

Cheers

**Comment by zeux** [comment]
The binary is built on GitHub actions entirely from source so it’s either the case that the GHA infrastructure is infected (very unlikely) or, more likely, it’s a false positive. I’ll double check what virustotal thinks a little later and see if Windows Defender has a way to report false positives like this.

**Comment by zeux** [comment]
VirusTotal thinks there's no issues here: https://www.virustotal.com/gui/file/4eb0ad66ef7c7c2ffc9180d94d01ef643934312a194b73af7c61ecfd18f9a61f?nocache=1

I've submitted this file as false positive here (link might be tied to my account so may not open, unsure):
https://www.microsoft.com/en-us/wdsi/submission/be4bcd30-19fa-4718-b21a-653fc5c2441f
