### ISSUE TITLE
Consider MESHOPT_-prefixed extensions

### ISSUE THREAD

**Issue by donmccurdy** [zeux/meshoptimizer#45]
As the `KHR_quantized_geometry` and `KHR_meshopt_compression` extensions are pseudo-extensions at this point, consider reserving the `MESHOPT_` prefix (or similar) in the glTF repository and using that for now. [Details are on GitHub](https://github.com/KhronosGroup/glTF/blob/master/extensions/README.md#promoting-extensions), but as a short summary:

- Vendor extensions like this are recommended for single-party needs and initial proposals.
- `EXT_` extensions are recommended for multi-party extensions that are not, for whatever reason, ratified by Khronos or protected by the Khronos IP framework.
- `KHR_` extensions are ratified by Khronos, and protected by its IP framework.

I like the idea of exploring official versions of both, but that would take some time, and best to prevent any confusion in meanwhile. Thanks! 🙂

**Comment by zeux** [comment]
`KHR_quantized_geometry` intends to just allow non-FLOAT attribute arrays for various geometric attributes, with no extra schema extensions - that seemed like something that could become KHR immediately to reduce spec churn.

For the compression extension, I was following DRACO naming scheme - my understanding is that DRACO mesh compression extension never went through the full cycle? - but I'm happy to start with MESHOPT prefix.

Does that make sense?

**Comment by zeux** [comment]
One alternative is to remove KHR_quantized_geometry from the generated files for the time being, since it's just a marker that in the future could be used by the validator, and change the compression extension name to MESHOPT_compression for now.

**Comment by donmccurdy** [comment]
I do agree that `KHR_quantized_geometry` seems simple enough that it could move pretty quickly, and I can't think of any reason it wouldn't be a KHR_-prefixed extension if it moves forward. That said I'm a little paranoid about developer confusion, and would still suggest a `MESHOPT_quantized_geometry` naming at least until you're ready to propose something on the glTF repository. Using some sort of extension is definitely preferable to omitting it, if the files would not pass validation with the modifications. Otherwise it just looks like a broken file to many tools.

The Draco extension was ratified by Khronos, including the [bitstream specification](https://google.github.io/draco/spec/).

**Comment by zeux** [comment]
Ok, I can change both to have `MESHOPT` prefix for now, but I'll probably want to propose `KHR` for the quantized geometry extension once this is all in good shape. Wrt Draco what I meant is that that extension immediately became KHR, although I guess the pending animation compression extension looks like it is following the longer route. (meshopt compression applies to both geometry and animations atm)

**Comment by donmccurdy** [comment]
> I can change both to have MESHOPT prefix for now, but I'll probably want to propose KHR for the quantized geometry extension once this is all in good shape...

Yes, that's totally fine.

> Wrt Draco what I meant is that that extension immediately became KHR, although I guess the pending animation compression extension looks like it is following the longer route...

There's no requirement that vendor or EXT_ extensions must exist before a KHR_ extension – with enough consensus the KHR_ version could certainly happen first. My concern was just that having stable/released software like gltfpack output Khronos-branded extensions that aren't listed under the [registry](https://github.com/KhronosGroup/glTF/tree/master/extensions#gltf-extension-registry) would likely confuse users.
