### ISSUE TITLE
error model.

### ISSUE THREAD

**Issue by copycd** [zeux/meshoptimizer#451]
a model that i attached is a samplemodel using on assimp library.
because mesh.indices.size() is zero.

static void optimizeMesh(Mesh& mesh, bool compressmore)
{
	if (compressmore)
		meshopt_optimizeVertexCacheStrip(&mesh.indices[0], &mesh.indices[0], mesh.indices.size(), vertex_count);
	else
		meshopt_optimizeVertexCache(&mesh.indices[0], &mesh.indices[0], mesh.indices.size(), vertex_count);
}

[BoxWithInfinites.zip](https://github.com/zeux/meshoptimizer/files/9274240/BoxWithInfinites.zip)

**Comment by zeux** [comment]
Hmm - are you running a Debug build? This works fine in debug build of gltfpack on Linux but it's probably not asserting on accessing an empty vector. I'm going to fix this nonetheless, just double checking - this should work fine in Release.

**Comment by zeux** [comment]
Thanks, reproduced with _GLIBCXX_ASSERTIONS and fixed.

**Comment by copycd** [comment]
I use Windows, Visual Studio 2022, Debug, Release. 
I need to check a little more. Thank you.
