### ISSUE TITLE
Split meshes can also be an optimization 

### ISSUE THREAD

**Issue by Maxxxel** [zeux/meshoptimizer#456]
Nice tool you got there, but for my purposes I need something that can split a gltf/glb mesh Into multiple meshes (with max_Vertices_Count and max_Faces_Count), as the desired game engine only supports maximum indices of 32.767.
Would it be possible to add such a feature or is it too complicated?

My current workaround is loading the model in Blender and reducing complexity :/

**Comment by zeux** [comment]
Mesh splitting isn't too complicated so it could be implemented I think. Are you sure the limit is 32767 vertices as opposed to 65535?

**Comment by Maxxxel** [comment]
I'm sure, the rever engineered Data says Face Indices are signed shorts :/ when I go above the value the model gets out of hand.

**Comment by zeux** [comment]
I would probably look into https://github.com/donmccurdy/glTF-Transform for this kind of involved processing - I don't know OTOH if it supports mesh splitting, but it tends to be better when you want to execute a series of specific processing commands, whereas gltfpack tends to be better at processing scenes optimally with little configuration.

**Comment by Maxxxel** [comment]
Thanks for the hint I'll check it out!

**Comment by zeux** [comment]
gltfpack doesn't do coordinate system transforms; similarly to above, this seems to be a task better suited for glTF-Transform (unsure if it already supports it or not).

**Comment by Maxxxel** [comment]
Thank for all 👌

**Comment by zeux** [comment]
Looking at this again, this is probably specific enough that glTF-Transform would be a better fit.
