### ISSUE TITLE
Possible to pass mesh weighting to optimizer?

### ISSUE THREAD

**Issue by fire** [zeux/meshoptimizer#46]
I was curious, is it possible to pass the mesh skinning association to the mesh optimizer as part of the vertex attributes?

**Comment by zeux** [comment]
Yeah - this is the intended use case. meshoptimizer doesn't currently care about the meaning of different attributes, and you're free to either add skinning bindings to the vertex structure (e.g. `uint8_t boneIndices[4]; uint8_t boneWeights[4];`), or have them as a separate attribute stream.

In other words, as far as meshoptimizer is concerned, skinning should be treated the same way as texture coordinates or normal data.

**Comment by fire** [comment]
Do I need to make sure every vertex relates to a specific face (non unique)? Not sure how to ensure that the skinned vertex is associated with the correct face.

**Comment by zeux** [comment]
It depends a bit on how your skinning data is specified.

I'd expect that skinning data is associated with vertices, not faces; if you have skinning data for face corners (e.g. 3 sets of bone influences for each triangle, one per vertex), then you might want to assemble a non-indexed stream of triangle vertices with skinning data, and then generate a unique index buffer - similar to how the demo program does this in `parseObj` function.

**Comment by fire** [comment]
I was able to get this to work for lodded meshes. It is a bit difficult to do this for lodded blend shapes...

**Comment by zeux** [comment]
Yeah, blend shapes are a bit painful to deal with. One useful strategy that might work - I'm fuzzy about your specific workflow so I'm not sure if it will help - is to pass the index of the vertex, assuming you have consistend blend shape topology, to meshoptimizer during various optimization stages as a vertex attribute; you can then reconstruct the vertex buffer with positions for all blend shapes using this index.

**Comment by fire** [comment]
The current workflow I'm trying:

* Begin with a mesh that has
  * an array vertex position and attributes
  * an array of array of blend shapes position and attributes
* Generate LOD levels to result in 5 arrays of indices
* Take the mesh data in the first step.
* Now both the original mesh and the lod mesh only differ in the indexes
* deindexing with blend shape awareness (stuck here)
* The mesh doesn't display because the vertex count is different in the blend shapes
* ???
* Create the mesh

**Comment by zeux** [comment]
When you generate LODs, the resulting index buffer points at the original vertex data which means that you should have consistent indexing between blend shapes - that is, you should be able to take an index buffer for any LOD and apply it to any blend shape. Is your goal to generate a small vertex buffer for each LOD / blend shape individually?

**Comment by fire** [comment]
I don't think so, I'm trying to optimize for mobile platforms though.

**Comment by zeux** [comment]
If you want to apply any remapping on the vertex data, it's sufficient to do this across all blend shapes.

For example, gltfpack does this as follows:

https://github.com/zeux/meshoptimizer/blob/master/tools/gltfpack.cpp#L560-L585

The array of streams contains all streams from all morph targets; here we generate the remap table using only the base target, and then apply the remap table to all streams.

When optimizing for vertex cache, gltfpack does something similar, again remapping all target streams
in sync:

https://github.com/zeux/meshoptimizer/blob/master/tools/gltfpack.cpp#L593-L602

Hopefully that helps.

**Comment by fire** [comment]
A bit swamped, will look into this.

**Comment by jpaver** [comment]
> std::vector<unsigned int> remap(total_indices); 
> size_t unique_vertices = meshopt_generateVertexRemapMulti(&remap[0], &mesh.indices[0], total_indices, total_vertices, &streams[0], streams.size()); 
 
I think remap in your first example has the wrong size - it should be sized to total_vertices right?

**Comment by zeux** [comment]
@jpaver yes that's correct, thanks - this was fixed a few weeks ago but the permalink reflected the old code - I've updated the comment above to refer to the current code.

**Comment by zeux** [comment]
I don't think there's any extra action items here so I'll close this for now, feel free to reopen / open a new issue if other questions arise.
