### ISSUE TITLE
Resolving mesh position misalignment during vertex quantization

### ISSUE THREAD

**Issue by gtolarc** [zeux/meshoptimizer#461]
When vertex quantization optimization is performed, the existing mesh is transformed into named nodeXX mesh with a TransformNode parent.
As you can see in the screenshot, a position shift occurs between this parent and child. Is this intentional or a bug?
Whatever it is, using the mesh itself is inconvenient because manual position correction is required.

You can make a transition with the parent TransformNode, but if you create an instances with the mesh, these instances do not have a parent node, so each position correction is required. (At least as far as I know)

Is there any good way to solve this problem?

![Screen Capture on 2022-08-16 at 22-09-22](https://user-images.githubusercontent.com/8623798/184887701-e5245b03-7942-4bdb-98d0-4d40684e8e2b.gif)

**Comment by zeux** [comment]
This is intentional - quantization requires a transform to move the mesh into the expected coordinate space. For quantized models it's expected that the transform node is used by the application instead of the source mesh.

**Comment by gtolarc** [comment]
@zeux Thanks for your kind reply. Then, when I want to create an instanced mesh based on the quantized mesh, do I always have to manually correct the position?

**Comment by zeux** [comment]
If you're instancing the mesh loaded from the resulting glTF file then you need to apply a correction matrix to your instance transforms; you can retrieve that matrix from the transform node, and then multiply all transforms with it, yeah. gltfpack does this automatically when using instancing extension, but that only applies when the instances are already in the source file.

**Comment by gtolarc** [comment]
@zeux Now I definitely understand. Anyone who does not know about vertex quantization and starts to use this tool is likely to go through the same process as me, so a simple guide will help the popularity of this tool. Thank you :)
