### ISSUE TITLE
meshopt_Stream's stride behavior

### ISSUE THREAD

**Issue by JesseRMeyer** [zeux/meshoptimizer#463]
The comment above the struct definition states `similar to glVertexPointer`, leading me to initially believe that if the stride is 0, then the stride is assumed to be equal to the size parameter (tightly packed).  But this is not true.  I think the common case for multiple vertex attribute streams (in the *multi case) are tightly packed, so I suggest considering changing this behavior.  Unless I am misunderstanding something.

**Comment by zeux** [comment]
Yes, stride must be greater than zero. I believe all existing functions that take stride parameters, whether via meshopt_Stream or directly, assert that stride is greater than zero - let me know if that wasn't the case!

I'm reluctant to change this - stride was required to be positive for years now, and many functions will need to be changed to adopt that special case. It's not always the case that elements are tightly packed, and I think uniform unsurprising interface is better than special case convenience.

However, it would probably be good to remove references to glVertexPointer to avoid confusion; glVertexPointer was only mentioned to indicate that 3 floats are going to be read from certain arrays when the function expects actual position values, but it looks like this is more harmful than helpful.
