### ISSUE TITLE
gltfpack: Scene hierarchy changed unexpectly

### ISSUE THREAD

**Issue by scarletsky** [zeux/meshoptimizer#469]
I am using `gltfpack 0.18`, this is the original glb data:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/2386165/185724411-e191ec10-a656-4577-98b4-8155d17dfc6a.png">

And after `gltfpack -cc -kn -km -ke`, the nodes data changed
<img width="626" alt="image" src="https://user-images.githubusercontent.com/2386165/185724504-259aa604-7f9c-4b1e-bf86-b0df43145100.png">

Is there any flags can keep the hierarchy ? Some of my process rely on the scene hierarchy...

**Comment by zeux** [comment]
See #424.

The short story is: it's impossible to not change the hierarchy when the quantization is used. When using 0.18, gltfpack will always change the hiearchy. The most recent builds of gltfpack (that can be downloaded from https://github.com/zeux/meshoptimizer/actions/runs/2886910574) relax this restriction when either `-noq` or `-vpf` is used, by preserving the parts of the hierarchy with named nodes.

**Comment by scarletsky** [comment]
I see. Thanks for your quick reply.
