### ISSUE TITLE
[gltfpacker] Feature request: add support for unlit materials (KHR_materials_unlit extension)

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [zeux/meshoptimizer#47]
Hi,

In order to test the models from the [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models/) more easily I've made a small set of scripts to download the latest models and run them through gltfpacker: https://github.com/TimvanScherpenzeel/gltfpacker-sample-model-test. It is very much hacked together but it does the job, perhaps parts of it can also be useful to you too.

I haven't spotted any bugs or unhandled cases except for a model with unlit materials (using the [KHR_materials_unlit](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit) extension). I think the objective of the extension is in line with the goals of gltfpacker.

Original
![Screen Shot 2019-07-03 at 21 53 07](https://user-images.githubusercontent.com/11870513/60621104-1bb9b780-9ddd-11e9-9a6c-03753f57a356.jpg)

gltfpacker
<img width="449" alt="Screen Shot 2019-07-03 at 21 46 36" src="https://user-images.githubusercontent.com/11870513/60620685-2c1d6280-9ddc-11e9-9e46-877d7b10a839.png">

[UnlitTest.zip](https://github.com/zeux/meshoptimizer/files/3356634/UnlitTest.zip)

Kind regards,

Tim

**Comment by zeux** [comment]
Oh, this is actually a bug - gltfpack tried to support unlit materials but clearly didn't do this correctly :)
