### ISSUE TITLE
gltfpack: produce incomplete gltf asset if source contains external images

### ISSUE THREAD

**Issue by wsw0108** [zeux/meshoptimizer#487]
And if we do NOT use basisu(ktx2).

```
npm install -g gltfapck
mkdir output
gltfpack -i glTF-Sample-Models/2.0/Avocado/glTF/Avocado.gltf -o output/test.gltf
```

The texture images are not copied to `output`.

**Comment by zeux** [comment]
This is by design but it would be possible to add an option to explicitly copy images into a target folder.
