### ISSUE TITLE
Expose `target_error` to gltfpack

### ISSUE THREAD

**Issue by FreakTheMighty** [zeux/meshoptimizer#494]
It would be helpful to have `target_error` exposed to gltfpack. If I understand this correctly, this could provide another tool for aggressively simplifying, while setting a lower floor for quality.

https://github.com/zeux/meshoptimizer/blob/7d8d3f79c3a4143616fc035afb0a4a2d1ca7982f/src/simplifier.cpp#L1423

**Comment by zeux** [comment]
Right now gltfpack sets the error automatically to 0.1f (meaning up to 10% deviation) when using aggressive simplifier. The slight difficulty in exposing a setting for this is that the error thresholds are actually different between normal mode and aggressive mode, so `-sa` ends up doing two attempts at simplification - once with `meshopt_simplify` with target error 1%, and once more if necessary with `meshopt_simpifySloppy` with target error 10%.

Are you looking to increase or reduce the error threshold?

**Comment by FreakTheMighty** [comment]
@zeux I think the main use case would be to remove as many triangles away while preserving a specific quality. To produce LODs I might do something like set the triangle target to 0, but vary the maximum error.
