### ISSUE TITLE
gltfpack removes custom properties

### ISSUE THREAD

**Issue by luke-han** [zeux/meshoptimizer#495]
As you can see in the image, I have set custom properties on the bones.
And if I compress the exported glb file with gltfpack, the custom property values are gone.
![image](https://user-images.githubusercontent.com/899934/196601322-1f35030a-fec1-4806-a829-b3d133e9c17b.png)

I've attached an exported glb file named `bone.glb` and a compressed glb file named `bone_comp.glb` to reproduce this issue.

[bone.zip](https://github.com/zeux/meshoptimizer/files/9816955/bone.zip)

**Comment by zeux** [comment]
Have you tried using `-ke` flag?

**Comment by luke-han** [comment]
@zeux 
OMG. It works! I thought it was not in the range of optimization.
