### ISSUE TITLE
What is the purpose of `vertex_positions_stride`?

### ISSUE THREAD

**Issue by aaronfranke** [zeux/meshoptimizer#501]
Link to the code: https://github.com/zeux/meshoptimizer/blob/1cfd09893292e5842ba44e93709779ea28639675/src/simplifier.cpp#L381

Introduced here: https://github.com/zeux/meshoptimizer/commit/e314803f6f41280f7b3bb18d19bda429f3fec669#diff-4dafd05605d62a05479353aaa1a80b1016b966eee22a0ca1e73039901fd2403eR319

This method has an argument for `vertex_positions_stride`, but I can't figure out what the purpose of this argument is.

* Is it to allow different-sized vectors, like Vector2 or Vector4? It doesn't seem so, because it looks hard-coded for 3 elements. The `v[2]` read will cause undefined behavior if the data contains Vector2.
* Is it to allow different-sized floats in the vectors? It doesn't seem so, since the whole method is hard-coded for `float`. If this was the goal, then it would make sense to provide an abstract type.

Is there a reason that this method doesn't use `sizeof(float) * 3` instead of having an argument for this?

**Comment by corporateshark** [comment]
>Is there a reason that this method doesn't use sizeof(float) * 3 instead of having an argument for this?

Yes. Position can be a part of vertex structure as follows:

```
struct Vtx {
   vec3 pos;
   vec3 normal;
   vec2 uv;
};
```

In this case, `vertex_positions_stride` should be `sizeof(Vtx)`.
