### ISSUE TITLE
AABB is incorrect at some models

### ISSUE THREAD

**Issue by daemyung** [zeux/meshoptimizer#503]
After running gltfpack to compress a model, AABB looks incorrect. I use a below command.

```
gltfpack -i model.glb -o compress.glb -cc
```

Below figure is before running gltfpack.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/7459074/198195573-df3c7bd4-9a67-45cf-a5b5-abd39012b0e9.png">

Below figure is after running gltfpack.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/7459074/198195500-7d8b0150-c657-4a23-8a1e-f1927e671c1d.png">

AABB should be equal to original when using gltfpack.

**Comment by daemyung** [comment]
You can have this model at [here](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphStressTest).

**Comment by zeux** [comment]
What viewer is this image from?

**Comment by daemyung** [comment]
I use [filament](https://github.com/google/filament)'s gltf_viewer.

**Comment by zeux** [comment]
Got it - yeah it looks like this code https://github.com/google/filament/blob/main/libs/gltfio/src/AssetLoader.cpp#L987-L988 needs to combine accessor min/max for the morph target with the mesh data, min/max is incorrect here since aabb data is absolute and min/max are relative.

**Comment by daemyung** [comment]
> Got it - yeah it looks like this code https://github.com/google/filament/blob/main/libs/gltfio/src/AssetLoader.cpp#L987-L988 needs to combine accessor min/max for the morph target with the mesh data, min/max is incorrect here since aabb data is absolute and min/max are relative.

Very correct. I'm fixing there exactly :).
