### ISSUE TITLE
meshopt_simplify doesnt reduce triangle count of meshes

### ISSUE THREAD

**Issue by Zeta48** [zeux/meshoptimizer#512]
I am integrating meshoptimizer in my engine. Goal is to implement an LOD system.
Unfortunately calls to meshopt_simplify always return the same number of indices than the input.

My code sample:
`
	/*
	struct FullVertex
	{
		Math::Vec3 position;
		Math::Vec3 normal;
		Math::Vec3 tangent;
		Math::Vec3 bitangent;
		Math::Vec2 texCoord;
	};
	*/
	
	void generateLOD(const Model::Mesh* mesh,
		std::vector<FullVertex>& outVertices,
		std::vector<unsigned int>& outIndices)
	{
		// Read the input vertex and index buffers.
		const std::vector<FullVertex>& inVertices = mesh->getVertices();
		const std::vector<unsigned int>& inIndices = mesh->getIndices();

		// The target index count.
		const float targetIndicesRatio = 3.0f;
		const size_t targetIndexCount = (size_t)(glm::max((nbFloat32)inIndices.size()/ targetIndicesRatio, 3.0f));

		// Allocate enough index memory for the simplification.
		outIndices.resize(inIndices.size());

		// The target error.
		const float targetError = 0.01f;

		// Perfom the mesh simplification.
		const size_t nbOutIndices = meshopt_simplify(&outIndices[0],
			inIndices.data(),
			inIndices.size(),
			reinterpret_cast<const float*>(inVertices.data()),
			inVertices.size(),
			sizeof(FullVertex),
			targetIndexCount,
			targetError);

		if (nbOutIndices != inIndices.size())
		{
			std::cout<<"Work done";
		}

		outIndices.resize(nbOutIndices);
		outVertices = inVertices;
	}
`

When run on the Sponza atrium meshes, the "Work done" is never reached. Am I doing something wrong or it is a library issue?  I am using the master branch code. I also tried release v018 but it has the issue too.  
![Sponza](https://user-images.githubusercontent.com/45646528/201802326-e01ad4d3-e88c-4ec7-aa7c-4f6639f3c6b1.jpg)
The sponza model is available here:  
https://github.com/Zeta48/Sponza-Atrium

Thanks for helping!

**Comment by zeux** [comment]
How many vertices and indices are there in some meshes that `meshopt_simplify` gets as an input? A prerequisite for the simplification algorithm is a "proper" index buffer that doesn't have duplicate vertices - if number of vertices is almost always equal to the number of indices, or if it's only ~2/3 of the number of indices, this is likely the reason (the latter suggests that the .obj loader you use simply tessellates quads without actually reusing vertices).
