### ISSUE TITLE
call gltfpack.exe many times whith -tc -noq, it seems to be deadlock

### ISSUE THREAD

**Issue by zuixiaosanlang** [zeux/meshoptimizer#517]
i call the exe like this using c#:
![image](https://user-images.githubusercontent.com/20105627/204434269-0bae98eb-108a-40c1-b107-fb8864f8ece5.png)

but it only can process some files, it may appear deadlock, 

i try on windows and linux， same problem.

if add -tj 1, it works ok

**Comment by zeux** [comment]
Does this happen with binaries from https://github.com/zeux/meshoptimizer/actions/runs/3535135005 (at the end of the page)?

When it hangs, how many images are there in the gltf file that's being processed?

**Comment by zuixiaosanlang** [comment]
@zeux 
same problem. i test it on windows using binaries you give.

some objs has 40 images

**Comment by zeux** [comment]
Okay - never mind, I can kinda reproduce this on macOS. I'll take a closer look.

**Comment by zeux** [comment]
Please check if the builds from https://github.com/zeux/meshoptimizer/actions/runs/3596164069 fix this.

**Comment by zuixiaosanlang** [comment]
@zeux 
it works ok now.

thanks
