### ISSUE TITLE
When creating meshlets using meshopt_buildMeshlets some clusters might not be connected

### ISSUE THREAD

**Issue by adiblev** [zeux/meshoptimizer#531]
Occasionally when building clusters from a given mesh, some of the clusters might integrate triangles that are not connected.
It is given that some triangles might remain as leftovers with minimal connectivity, but connecting them to reduce the amount of clusters is usually a mistake.

I suggest either not allowing this, or accompanying this with a flag (on/off) or a distance threshold.

**Comment by zeux** [comment]
I’m not sure I agree with this being a mistake. For mesh shading implementation on desktop my assessment has been that under filling meshlets results in more efficiency loss than the extra culling is worth. That said I’m sure it’s situational - let me know if you have data that contradicts this.

An issue with unconditional splitting, even based on the flag, is that it results in much larger worst case number of meshlets. Maybe it would make sense to provide a second limit for triangles per meshlet and have the split only happen if the number in the specified range is reached…

**Comment by adiblev** [comment]
I do see your point, there is no great solution here other than optimizing and trying to run again with different grouping that will reduce this aspect.
At the end of the day you are right and indeed it's a battle between larger amount of meshlets on one side and connectivity on the other for triangles that were left behind.
We can close this one or set the flag / TH to be as low priority.
