### ISSUE TITLE
Meshlets bounding data (bounding sphere and visibility cone) is sometimes partially bogus

### ISSUE THREAD

**Issue by adiblev** [zeux/meshoptimizer#532]
When using the function meshopt_computeMeshletBounds to generate the meshlets bounding data, normal can be zero at times for clusters that are of non zero size and frequently the cut off half angle will not be accurate and will be over protective.

**Comment by zeux** [comment]
Do you have an example input that reproduces the problem and some sense wrt how common this is? Normally when normals cancel each other out, the cluster cone representation is redundant even with a best cone fit but I’m curious to see data on this as it can be improved.

**Comment by adiblev** [comment]
Absolutely, however I'm running this on multiple mesh objects and the the problem is quite evident.  In the case you described (should be relatively rare) a simple solution will be to remove the first normal, then average and finally calculate the cone based on the difference between the average normal from the rest.

I will go back to my RenderDoc and provide a snap shot of a buffer I reviewed.
