### ISSUE TITLE
How to merge meshes by meshoptimizer.js lib?

### ISSUE THREAD

**Issue by hookex** [zeux/meshoptimizer#535]
Mesh meshes of model by gltfpack cli tool is easy!
But how to merge meshes by meshoptimizer.js lib in the node.js environment?

**Comment by zeux** [comment]
meshoptimizer.js is a low-level library that is designed to be integrated into mesh processing pipelines. It doesn't provide end to end glTF processing and it doesn't provide basic algorithms that are easy enough to implement in JS.

If you need to merge meshes as part of glTF processing, you can use gltfpack in node.js as an executable, or use glTF-Transform as a library if you need a more algorithmic approach.
If your processing is unrelated to glTF, you'll need to implement mesh merging yourself.
