### ISSUE TITLE
gltfpack: LOD generation

### ISSUE THREAD

**Issue by blanxdev** [zeux/meshoptimizer#539]
Hi,

I thought it might be useful to add LOD generation support.

The settings can be specified like this:

-tc
-si 1.0,0.5,0.1
-tl 2048,1024,256
-sa false,false,true

So if one wants to modify settings per level, one has to always use the same count of options

**Comment by zeux** [comment]
Currently, glTF does not have LOD extensions that are universally supported. The only vendor extension for this is MSFT_lod and it's in semi-deprecated status in that most renderers don't support it. There's a newer EXT_node_lod [extension](https://github.com/KhronosGroup/glTF/pull/2228) that's being proposed; I'm not sure what the status of that is.

Even with the LOD extensions, they only cover geometry/materials - not textures. So if multiple levels of texture detail are desired, it really just requires multiple glTF files -- which can be achieved today by running gltfpack multiple times with different options.

If EXT_node_lod or an equivalent vendor neutral extension gets added to glTF eventually then it would make sense to support it in gltfpack.

**Comment by zeux** [comment]
Looking at the extension I mentioned it doesn't look like there's a lot of traction. For now I will close this since it requires changes to glTF spec to support, if/when they happen I'll reopen this.
