### ISSUE TITLE
support tinygltf

### ISSUE THREAD

**Issue by newpeople123** [zeux/meshoptimizer#577]
I want to integrate gltfpack in my project, but my project uses the gltf file parsed by tinygltf. I don't want to export the file and use gltfpack to read the file. This will increase data processing time. Can you provide a code example of tinygltf:: Model Type conversion cgltf type?

**Comment by zeux** [comment]
I think your best bet is to save the file to .gltf. Certainly gltfpack isn't going to switch to tinygltf; it's likely possible to convert the scene in-memory from tinygltf data structure to cgltf, but it's a fair amount of work so I would not recommend it.
