### ISSUE TITLE
custom atrribute

### ISSUE THREAD

**Issue by newpeople123** [zeux/meshoptimizer#578]
When I handle a task with_ When using the gltf of BATCHID, the gltfpack will prompt "Warning: assigning custom attribute _BATCHID in primitive 0 of mesh 0", but this attribute is very important to me. Can I keep the custom attribute in future versions?

**Comment by zeux** [comment]
This should already work in latest versions; if you're using v0.19 you'd need to use latest master instead. See https://github.com/zeux/meshoptimizer/pull/568.
