### ISSUE TITLE
gltfpack: Validation errors (MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT)

### ISSUE THREAD

**Issue by Snafuh** [zeux/meshoptimizer#58]
Hi

The optimized files created via gltfpack.exe seems to contain some incorrect attributes and cannot be opened by some gltf importer (e.g. the Windows 10 build in 3D viewer doesn't open the files).

The gltf viewer on https://gltf-viewer.donmccurdy.com/ is able to open the files but returns following errors

```
MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT | Invalid accessor format '{VEC3, BYTE normalized}' for this attribute semantic. Must be one of ('{VEC3, FLOAT}'). | /meshes/0/primitives/0/attributes/NORMAL
-- | -- | --
MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT | Invalid accessor format '{VEC3, UNSIGNED_SHORT}' for this attribute semantic. Must be one of ('{VEC3, FLOAT}'). | /meshes/0/primitives/0/attributes/POSITION
MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT | Invalid accessor format '{VEC2, UNSIGNED_SHORT}' for this attribute semantic. Must be one of ('{VEC2, FLOAT}', '{VEC2, UNSIGNED_BYTE normalized}', '{VEC2, UNSIGNED_SHORT normalized}'). | /meshes/0/primitives/0/attributes/TEXCOORD_0
ACCESSOR_NON_UNIT | 2368 accessor elements not of unit length: 0. [AGGREGATED] | /accessors/0
```

**Comment by zeux** [comment]
Yeah this is known/expected; as mentioned in the readme, technically the gltf files are not standard compliant and rely on non-standardized extensions to store data.

Having said that, it would be nice to have the builtin Win10 viewer work. I have noticed this before but didn’t pay much attention because I have seen many valid gltf files that it doesn’t open either. I will take a closer look.

**Comment by zeux** [comment]
I'm going to keep this issue open for tracking; the core problem is due to quantized attributes not having a standard extension that validator recognizes, and I'm looking into extension standardization for this.

**Comment by zeux** [comment]
I've filed the proposal for an extension that can solve this issue - when/if the extension is ratified, gltfpack will be changed to comply with that extension (and when validator is changed accordingly, the validation errors should go away)

https://github.com/KhronosGroup/glTF/pull/1673

**Comment by zeux** [comment]
This is waiting for https://github.com/KhronosGroup/glTF-Validator/pull/124 to get merged, once it is I can close this. 

The Windows 10 viewer would need support for the extension to work; I don't have a lot of visibility into the entire software stack there but I've filed https://github.com/microsoft/glTF-SDK/pull/51 which, when/if merged and propagated all the way to the viewer should result in the extension being supported as well.

**Comment by zeux** [comment]
Closing as the validator change was merged. gltfpacked files should validate cleanly on recent builds - please feel free to open new issues if this is not the case for some files.
