### ISSUE TITLE
gltfpack: export obj?

### ISSUE THREAD

**Issue by gwald** [zeux/meshoptimizer#589]
I know it isn't core to your project, but thought I would ask anyway, because it's an excellent app!
Looking at using this for gamedev 3D models, but having issues with the .glb/.gltf formats (converting them back to .obj via assimp, no texture and no UV's - not looking for support here).

Would it be possible to export the optimized mesh in obj format? 
Possibly like a debugging mode, seeing the verts, uv, faces in text etc.

I guess the mtl file wouldn't need to be recreated as it would be the same.

**Comment by zeux** [comment]
Upon some reflection I think this is outside the scope of meshoptimizer/gltfpack.

Meshoptimizer is already providing algorithms that are easy to integrate. It should be fairly straightforward to build an .obj processing tool using it.

gltfpack is designed as an opinionated tool that optimizes glTF files. It does support .obj files as an input, the motivation there is primarily that some files are just not available other than in .obj format, so it's easier to test the tool if it supports .obj inputs. Additionally, .obj is a simple format and as such any .obj file can be represented reasonably well by glTF structures.

The reverse doesn't quite hold. To get from glTF scene structure back to .obj, you need to perform a set of simplifications to the structure to get back to the small subset that works in .obj. The indexing is different, and to optimize it for .obj output size you may want to process the indices in a different way than you do for glTF as glTF files are render-ready, so the structure is different. Quantization isn't representable in .obj so it needs to be disabled, which changes defaults based on output file format. There's probably a bunch of other issues, like material roundtripping.

These could be mitigated by making a separate .obj to .obj processing pipeline. But gltfpack isn't designed for that, and .obj parsing code that exists there right now targets cgltf scene structures, so at this point we're past "maybe gltfpack can also output .obj files" and way into "maybe gltfpack can also have an independent .obj to .obj optimizer".

Plus .obj files aren't even efficient as a representation. Any pipeline that uses .obj -> gltfpack -> .obj would benefit from upgrading the tail of the pipeline to support .gltf.

Of course it's fine that existing tools like assimp can be inserted into the processing along with gltfpack to get here, but handling this in a first-class manner isn't aligned with the goals of this project.
