### ISSUE TITLE
Object space mesh error from meshopt_simplify()?

### ISSUE THREAD

**Issue by ienapliss** [zeux/meshoptimizer#59]
I kinda calculate an approximate error metric roughly based on hausdorff distance between the 2  mesh after generating the simplified one. Is there any chance to avoid this calculation and use some consistent object space error metric used internally by meshopt_simplify()?

Thanks in advance.
BTW very handy library. much appreciated.

**Comment by zeux** [comment]
So in theory the internal error that meshopt_simplify computes could be close enough to the error metric you're computing.

Here's a quick & dirty diff to compute this - obviously if this is useful this will have to be integrated into the interface in a cleaner way, and the error can be computed more quickly, but it would be good to understand first whether this works for you.

After this patch, global `meshopt_error` will contain the linear error relative to the mesh bounds (similar to input parameter `target_error`), and `meshopt_deviation` will contain the world-space value.

Would be interesting to know how close this gets to Hausdorff distance you compute.

```
diff --git a/src/simplifier.cpp b/src/simplifier.cpp
index 8f58934..50f0e87 100644
--- a/src/simplifier.cpp
+++ b/src/simplifier.cpp
@@ -368,7 +368,7 @@ struct Vector3
 	float x, y, z;
 };
 
-static void rescalePositions(Vector3* result, const float* vertex_positions_data, size_t vertex_count, size_t vertex_positions_stride)
+static float rescalePositions(Vector3* result, const float* vertex_positions_data, size_t vertex_count, size_t vertex_positions_stride)
 {
 	size_t vertex_stride_float = vertex_positions_stride / sizeof(float);
 
@@ -406,6 +406,8 @@ static void rescalePositions(Vector3* result, const float* vertex_positions_data
 		result[i].y = (result[i].y - minv[1]) * scale;
 		result[i].z = (result[i].z - minv[2]) * scale;
 	}
+
+	return extent;
 }
 
 struct Quadric
@@ -1096,6 +1098,9 @@ unsigned char* meshopt_simplifyDebugKind = 0;
 unsigned int* meshopt_simplifyDebugLoop = 0;
 #endif
 
+float meshopt_error; // temporary hack to "return" the error
+float meshopt_deviation; // temporary hack to "return" the error
+
 size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices, size_t index_count, const float* vertex_positions_data, size_t vertex_count, size_t vertex_positions_stride, size_t target_index_count, float target_error)
 {
 	using namespace meshopt;
@@ -1139,7 +1144,7 @@ size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices,
 #endif
 
 	Vector3* vertex_positions = allocator.allocate<Vector3>(vertex_count);
-	rescalePositions(vertex_positions, vertex_positions_data, vertex_count, vertex_positions_stride);
+	float extent = rescalePositions(vertex_positions, vertex_positions_data, vertex_count, vertex_positions_stride);
 
 	Quadric* vertex_quadrics = allocator.allocate<Quadric>(vertex_count);
 	memset(vertex_quadrics, 0, vertex_count * sizeof(Quadric));
@@ -1150,9 +1155,10 @@ size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices,
 	if (result != indices)
 		memcpy(result, indices, index_count * sizeof(unsigned int));
 
+	float worst_error = 0;
+
 #if TRACE
 	size_t pass_count = 0;
-	float worst_error = 0;
 #endif
 
 	Collapse* edge_collapses = allocator.allocate<Collapse>(index_count);
@@ -1208,7 +1214,6 @@ size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices,
 		size_t new_count = remapIndexBuffer(result, result_count, collapse_remap);
 		assert(new_count < result_count);
 
-#if TRACE
 		float pass_error = 0.f;
 		for (size_t i = 0; i < edge_collapse_count; ++i)
 		{
@@ -1218,9 +1223,11 @@ size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices,
 				pass_error = c.error;
 		}
 
-		pass_count++;
 		worst_error = (worst_error < pass_error) ? pass_error : worst_error;
 
+#if TRACE
+		pass_count++;
+
 		printf("pass %d: triangles: %d -> %d, collapses: %d/%d (goal: %d), error: %e (limit %e goal %e)\n", int(pass_count), int(result_count / 3), int(new_count / 3), int(collapses), int(edge_collapse_count), int(edge_collapse_goal), pass_error, error_limit, error_goal);
 #endif
 
@@ -1243,6 +1250,9 @@ size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices,
 		memcpy(meshopt_simplifyDebugLoop, loop, vertex_count * sizeof(unsigned int));
 #endif
 
+	meshopt_error = sqrtf(worst_error);
+	meshopt_deviation = meshopt_error * extent;
+
 	return result_count;
 }
 
```

**Comment by ienapliss** [comment]
Thank you for the quick answer!

I can confirm you that I could use use the world-space 'meshopt_deviation' as a replacement for the old object-space error I roughly calculated by my naive Hausdorff implementation. 

I noticed it is smaller than my result, so I assume it is a more accurate estimation than my previous approximation. I was just using a quick point-triangle_segments distance, not even a real point-triangle distance (so a little embarrassing estimation for a quick automatic lod switching).

**Comment by zeux** [comment]
The error that the simplifier computes is somewhat hard to define exactly because it's based on a normalized quadric error. When just a single edge collapse is involved, it's just a square of the distance, but when multiple collapses are involved it becomes something like a quadratic mean I think. I'm fuzzy about this because the normalization of the quadric is unusal and doesn't occur in the literature, and I haven't derived what *exactly* happens after a series of collapses :)

It's great to know that it's close enough though - it can definitely be useful to determine the LOD switching distances. I will look into exposing this properly.

**Comment by ienapliss** [comment]
Oh I see... now it makes more sense. Thank you!

**Comment by reduz** [comment]
By the way, I also tested that patch (modified it a bit in style but basically the same code), and it works excellent. Can't wait for this to be added so we can use upstream version. Thanks hugely!
![lod1](https://user-images.githubusercontent.com/6265307/102530266-d3995e00-407f-11eb-8c1d-6b29adb3e488.gif)
