### ISSUE TITLE
gltfpack: keep obj hierarchy and name

### ISSUE THREAD

**Issue by kzhsw** [zeux/meshoptimizer#595]
Motivation:
Currently gltfpack flattens and merges all obj meshes with the same material, so mesh hierarchy and name got lost even if `-kn` is passed.

Proposal:
With `-kn` argument, keep hierarchy and name from obj meshes, and do not merge it.
With `-km` argument, keep name from obj materials, and do not merge named obj materials.

Alternative:
[obj2gltf](https://github.com/CesiumGS/obj2gltf/) keeps hierarchy and name by default.

**Comment by zeux** [comment]
What do you mean by hierarchy? .obj files don't have transforms, only groups, from what I understand.

**Comment by kzhsw** [comment]
> What do you mean by hierarchy? .obj files don't have transforms, only groups, from what I understand.

Node name and hierarchy, like this:
![image](https://github.com/zeux/meshoptimizer/assets/120431159/550d2d09-4501-4eac-97c7-576488b244dd)

**Comment by zeux** [comment]
Right - I think the `__root__` name here is synthesized either by obj2gltf or Babylon.js. The object and material names can be kept though.
