### ISSUE TITLE
Add dequantization functions

### ISSUE THREAD

**Issue by JohnAlcatraz** [zeux/meshoptimizer#597]
There do not appear to be any dequantization functions? There is `meshopt_quantizeHalf` for example, but there is no `meshopt_dequantizeHalf` that turns the quantized value back into a float value. 

I'm not sure if I might be missing something, but quantization functions without dequantization functions seem a bit limited in helpfulness, since any quantized value also needs to be turned back into a regular value once it should actually be used - and if the library doesn't offer a function for that, that seems to be an issue. 

If a way to do this exists already in this library, then an explanation of this is missing from the readme, which explains how to quantize a normal or position, but never mentions anything about how to dequantize it.

**Comment by zeux** [comment]
The expectation currently is that the quantized values will be dequantized on the GPU using fixed function vertex configuration / using the shader math, which is why the dequantization functions are indeed missing.

**Comment by JohnAlcatraz** [comment]
Ok, but even if the values are expected be dequantized on the GPU, then someone still needs to write the code for the dequantization there that matches the quantization code of this library. And for that, having a reference implementation of the dequantization in C/C++ in this library would be very helpful, since porting some existing C/C++ code to HLSL is definitely easier than manually having to come up with the correct dequantization code.

In my case, I do not have control over the GPU-side of things, so I only use this library with quantization to reduce the size of a saved mesh on disk. So after loading it from disk I do need to dequantize the mesh in C++ before sending it to the GPU, so I'd just use dequantization functions of the library directly in C++ if they would exist.

For now, I let GPT-4 generate a "opposite of `meshopt_quantizeHalf`" function, it seems to work well for me so far:

```cpp
inline float meshopt_dequantizeHalf(unsigned short h)
{
	union { float f; unsigned int ui; } u;
	unsigned int s = (h & 0x8000) << 16;
	unsigned int e = (h >> 10) & 0x1F;
	unsigned int m = h & 0x3FF;

	// Handle zero, denormals, infinity, and NaN
	unsigned int exp;
	if (e == 0)
	{
		exp = (m != 0) ? ((127 - 14) << 23) : 0;
		m = (m != 0) ? (m << 13) : 0;
	}
	else if (e == 31)
	{
		exp = (m != 0) ? 0x7F800000 : 0x7F800000;  // NaN or infinity
		m = m << 13;
	}
	else
	{
		exp = (e + 127 - 15) << 23;  // normalized number
		m = m << 13;
	}

	u.ui = s | exp | m;
	return u.f;
}
```

**Comment by zeux** [comment]
> Ok, but even if the values are expected be dequantized on the GPU, then someone still needs to write the code for the dequantization there that matches the quantization code of this library.

Not really - the half-precision format is standardized and all GPUs support it natively. The integer formats are also supported natively through normalized formats by every graphics API, but of course for those the dequantization function is just a multiplication/division - which you can find in the comments. This should probably be spelled out in README.

It looks like for your specific case of encoding & decoding halfs on CPU it might indeed be useful to add a dequantization function, I'll take a look at adding that..

**Comment by JohnAlcatraz** [comment]
Ah, thanks! I did not know that it's actually "the" half-precision format, I thought it would be "some" half precision quantized format that you specifically created for this library. I know that some people spend a lot of time with coming up with new quantization algorithms for neural networks to get them down to just 2 or 3 or 4 bit, so I thought it would be similar here, that you came up with some fancy quantization algorithm that's especially good for mesh data.

It would definitely be good to mention then in the Readme and the comment of the functions that the quantization functions are just for the standardized format. That actually makes it much easier for me as well, I really don't need to use that function at all and can just use the native Unreal Engine FFloat16 type, since I'm using Unreal Engine and it already has that native type for half-precision floats, if this library doesn't end up creating anything else than a "regular" half-precision float.

For people who aren't using an engine/framework that already offers a native half-precision float type, having dequantization functions in this library would still be very useful though.
