### ISSUE TITLE
MorphTarget Names are overwritten 

### ISSUE THREAD

**Issue by arpu** [zeux/meshoptimizer#61]
i have this exported glb model with vertexGroups and MorphTargets after i use the gltfPack optimizer the MorphTarget Names get overwriten with MorphTarget1-xxx

original glb 
https://drive.google.com/open?id=1j7sPaSm1ahllFQo0Vd41oiU6asmi1RdF
optimzed
https://drive.google.com/open?id=1YT2a3iATYZc0TC8DLI00RPlNcbisSMX7

tested with https://gltf-viewer.donmccurdy.com

**Comment by zeux** [comment]
Yeah, gltfpack currently doesn't preserve mesh.extras.targetNames which is a non-standard extension (although mentioned in the spec). It does make sense to support it, but it's not completely straightforward - will need to look into it.

**Comment by zeux** [comment]
This is now fixed; also added a couple of small items to the TODO list that can reduce the file size here which will get done at some point in the future.
