### ISSUE TITLE
Having a big object (scaled), effects other objects' geometries in a scene.

### ISSUE THREAD

**Issue by enesaltinkaya** [zeux/meshoptimizer#645]
Hi, i want to first say thanks so much for this awesome project.
When I place a simple plane and scale it 100 or 1000 other objects in the scene lose detail.
I made a quick video showing the issue.

I have this script, exports .blend file to .glb, then runs gltfpack on it.
I also tried loading the same file on https://sandbox.babylonjs.com/ and https://gltf-viewer.donmccurdy.com/, they showed the same result.

https://github.com/zeux/meshoptimizer/assets/8594559/9c381828-a5d2-4204-ae31-acc8b402dce3

**Comment by zeux** [comment]
Yeah this is a known issue with large scales; tracked in #433. You can use -vpf command line option as a workaround for now, or -kn will also often fix the issue. If you can share the model in question that would be great since it will help make sure the eventual fix will improve it.

**Comment by enesaltinkaya** [comment]
[MainMenu.blend.zip](https://github.com/zeux/meshoptimizer/files/13773423/MainMenu.blend.zip)
.blend and .glb files are in the zip file.

I noticed -kn paremeter helps if I don't apply the scale in blender.

Thanks!

**Comment by zeux** [comment]
Looking closer at this report and I think it's the exact same cause as #433; I'm going to close this as a duplicate, the actual fix will come as part of #433. `-vpf` can be used as a workaround in the meantime.
