### ISSUE TITLE
ADD Merge Materials

### ISSUE THREAD

**Issue by zhaoyuanmeng** [zeux/meshoptimizer#650]
Can you add the function of the same material? thank you.

**Comment by zhaoyuanmeng** [comment]
Optimize materials by finding and removing identical duplicates. If multiple materials have the same properties, only one will be kept.

**Comment by zeux** [comment]
That's already implemented and is enabled by default, assuming you're talking about gltfpack (similarly to meshes, `-km` disables merging for named materials)
