### ISSUE TITLE
gltfpack: Simplification take in account the vertex color

### ISSUE THREAD

**Issue by Makio64** [zeux/meshoptimizer#652]
Would be nice if the algorithm take in account the vertex color to preserve the shape when of differents vertex color zone, here an example : 
![image](https://github.com/zeux/meshoptimizer/assets/213351/3d309cc5-0297-4605-acf5-938eed15149c)
![image](https://github.com/zeux/meshoptimizer/assets/213351/fa3170f8-a4bd-47d2-ac23-0243994f74f0)

The mouth area is particulary destroy in this example while there is so many other triangle to collapse,

The model which have no texture is good to test, all copyright to his author from sketchfab - free download : 
https://sketchfab.com/3d-models/bananya-birbo-900ce1ec328e486296cfee70b9b13a45

**Comment by zeux** [comment]
Yeah I planned to add this eventually, need to figure out how to activate this from command line and configure best. The simplifier now supports attribute weighted simplification, it just hasn't made its way to gltfpack. Quickly added this just to check what the results on this model would be and they seem good, this is 0.25 simplification ratio (1/4x triangles), current master vs attribute aware simplification.

![image](https://github.com/zeux/meshoptimizer/assets/1106629/9a23d828-7208-4cf6-b5be-5592c243bdfe)

![image](https://github.com/zeux/meshoptimizer/assets/1106629/ab2b05b4-bd97-4348-a321-83f8a725a7e5)

Will work on this in the near future.

**Comment by Makio64** [comment]
Attribute aware looks so much better and I think this mesh is cool to test it :)
