### ISSUE TITLE
Custom attributes ( for example IDs)

### ISSUE THREAD

**Issue by RyugaRyuzaki** [zeux/meshoptimizer#665]
This library is amazing. It would help a lot if there were more custom attributes

**Comment by zeux** [comment]
Assuming you mean gltfpack, it supports ID attributes in the latest version (0.20); the attribute needs to be named "_ID", "_BATCHID" or "_FEATURE_ID_n" for this to work. Feel free to suggest additional naming schemes to support, these were the ones that are commonly used in the ecosystem.
