### ISSUE TITLE
gltfpack: Output GLTF is invalid if input scene has missing image files

### ISSUE THREAD

**Issue by Cyphall** [zeux/meshoptimizer#675]
When optimizing a GLTF file which has image entries referencing missing files, the exported image entries have neither their `uri` property nor their `bufferView` property defined.
[According to this JSON schema in the specs](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#schema-reference-image), such entries are invalid.

When optimizing, gltfpack logs warnings about skipping these missing images entries to the console, which means it already is aware of this possibility.
As such, I would expect it to produce a valid GLTF file by simply copying these entries to the output file without any processing.

(related to KhronosGroup/glTF#2377)

**Comment by zeux** [comment]
I'm not sure if copying the URI unconditionally is always a good idea: if the output is a GLB file, I'd expect no external references and there might be issues if the target application doesn't expect that any URIs are preserved (eg maybe it's a URI that can be used maliciously somehow). Maybe in that case an empty URI would suffice...

**Comment by arpu** [comment]
@zeux i was able to get a model with this problem ( looks like it from the hubs exporter) 
i send you  the glb per mail

**Comment by Cyphall** [comment]
Yeah I didn't include a sample (probably should have, sorry) but to confirm this issue, I used [this one](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/BoxTextured/glTF) from the glTF-Sample-Assets repo and simply removed the png file.

**Comment by zeux** [comment]
One other potential cause here is that when using `-tc`, if the image path is valid but it refers to an invalid image (eg format encoding issues), Basis texture compressor will fail to process the image - as it should - and the image object will be left blank, which will also make the asset's JSON invalid.
