### ISSUE TITLE
Uncompress a model using gltfpack

### ISSUE THREAD

**Issue by famda** [zeux/meshoptimizer#703]
Hey!

I'm using gltfpack to make some experiences with some glb's.
Is it possible using gltfpack to revert back a model that was compressed using the -c or -cc options?

Thanks in advance.

**Comment by zeux** [comment]
Yes, this is possible as of last week :) binaries here for example https://github.com/zeux/meshoptimizer/actions/runs/9406249617 if you don't want to build latest gltfpack yourself. You can now just run gltfpack again and not specify `-c`/`-cc` and you'll get a decompressed model. (relevant PRs: https://github.com/zeux/meshoptimizer/pull/691, https://github.com/zeux/meshoptimizer/pull/700)

**Comment by famda** [comment]
Awesome! I'll try it out.

Is there any expected date to build a new release on the releases page?

Thanks.

**Comment by zeux** [comment]
Not sure, but probably a couple months - there's usually a couple releases per year but I want to spend some more time on core library improvements before releasing the next version.
