### ISSUE TITLE
Simplification should recognize and handle UV mirroring seams

### ISSUE THREAD

**Issue by Makio64** [zeux/meshoptimizer#718]
Rare case but on some models, simplification lead to UV artefacts : UVs are getting fully streched (same value on both vertices) when many other triangles could have been optimized instead, I suggest to give a lower priority to simplify/remove vertices/faces of the mesh leading to these results.

It might also be a bug in the way the uvs get re-assigned.

The model used to illustrate this example : 
https://www.dropbox.com/scl/fi/po761ykdiqdmtbzd9fitf/rhino.glb?rlkey=s6jp06vtr4id0opnv76wwys1p&dl=0

Before simplify : 
<img width="527" alt="Screenshot 2024-07-08 at 16 25 05" src="https://github.com/zeux/meshoptimizer/assets/213351/080e3431-bef9-4f61-811d-c5dbe638cf40">

After simplify :
<img width="536" alt="Screenshot 2024-07-08 at 16 14 54" src="https://github.com/zeux/meshoptimizer/assets/213351/2da68c85-190d-441b-a59b-3789170bed2b">

**Comment by zeux** [comment]
Are UVs mirrored here? If so then yeah it’s a known issue atm, and will get addressed eventually.

**Comment by Ipotrick** [comment]
Is there currently no way to prevent this issue with the meshoptimizer directly?

**Comment by zeux** [comment]
Not currently; it's on a future roadmap to provide some simpler way along the lines of what gltfpack is doing manually by exposing a way to request individual vertices on the UV seam to be treated as seams without having to duplicate vertices. Currently you either have to do what gltfpack is doing, or if your geometry has correct tangents they should automatically solve the issue as well.

**Comment by Ipotrick** [comment]
Dumb question, but would it work to simply pass uvs as attributes within meshopt_simplifyWithAttributes to combat this for now?

**Comment by Ipotrick** [comment]
I quickly tried it and passing uvs to meshopt_simplifyWithAttributes  fixes the issue nicely for me. I think this works for me for now 👍

**Comment by Makio64** [comment]
@Ipotrick I'm interested by this solution, so do you mean you're adding a very small random to the uvs ? like between ~0.000001  /  -0.000001 ?

**Comment by Ipotrick** [comment]
@Makio64 i simply list the uvs as attributes as well with a weight of 1.0f. As the uvs already dont vary very much between vertices a weight of 1.0f seems to prevent a lot of uv "miss simplifications" while not effecting overall mesh quality/ simplification level.
