### ISSUE TITLE
gltfpack: points cloud conversion

### ISSUE THREAD

**Issue by skemaikin** [zeux/meshoptimizer#729]
Hi! 
I've got a problem using gltfpack for conversion gltf-file containing points cloud into the glb file. After conversion the result is:
![image](https://github.com/user-attachments/assets/65e1922d-1db7-4fa7-a8fc-861a1866e233)

Source gltf: https://drive.google.com/file/d/1SeU-dP6gj6j2BFLEEMRTdm0p59vOD1C0/view?usp=sharing

**Comment by zeux** [comment]
What version are you using? This was briefly a problem in master but it was fixed here https://github.com/zeux/meshoptimizer/commit/5806d7774487b69240cb952e63746ed216847fa1 and I was under an impression that no versioned release had the issue.

**Comment by skemaikin** [comment]
> What version are you using? This was briefly a problem in master but it was fixed here [5806d77](https://github.com/zeux/meshoptimizer/commit/5806d7774487b69240cb952e63746ed216847fa1) and I was under an impression that no versioned release had the issue.

Sorry, my fault. Latest version works fine!
