### ISSUE TITLE
Keep textures in folder they started in

### ISSUE THREAD

**Issue by sotrh** [zeux/meshoptimizer#734]
I have a model from Sketchfab that has it's textures in a `textures` folder. When running gltfpack, the textures get duplicated to the same directory as the gltf file. This means we have two copies of the textures. It would be nice to have `gltfpack` keep textures in the folder they were found in perhaps behind a setting.

I tried `-tr`, though that didn't seem to work, nor am I sure what that option is supposed to do.

**Comment by zeux** [comment]
`-tr` keeps the original references without any modification and the expectation is that the caller manages the texture placement themselves. That also disables any copying. This should be the option to use here.

**Comment by zeux** [comment]
(oh, if you're using `-tc` then `-tr` does nothing because it's impossible to preserve the texture paths and at the same time change the content)
