### ISSUE TITLE
Simplification should prune topologically separate components

### ISSUE THREAD

**Issue by Ono-Sendai** [zeux/meshoptimizer#764]
Hi,
I'm running into this problem a lot, here is an example mesh on which it occurs.

![unsimplified gallery non wireframe](https://github.com/user-attachments/assets/7afd1804-f3c4-4285-8ae2-7b6a797b8af7)

![unsimplified gallery](https://github.com/user-attachments/assets/7c1180d2-fbd0-4283-a8df-3d71ab20f3d1)

The mesh has a bunch of small items in it (the cylindrical spotlights) that are topologically separate.  As a result of that, meshopt_simplify / meshopt_simplifyWithAttributes can't remove them (as documented).

This is the result of meshopt_simplify:

![simplified without attributes](https://github.com/user-attachments/assets/f439fe0c-fb9a-4721-b941-bae17ae22665)

The total number of triangles is only slightly reduced.

So then I call meshopt_simplifySloppy, which successfully removes the spotlights.  Unfortunately meshopt_simplifySloppy seems to merge vertices aggressively, resulting in pretty incorrect shading normals on the room itself.  See attached pics.

![simplified sloppy](https://github.com/user-attachments/assets/35068caf-8e09-47de-a0fb-514b72e43e45)
![simplified sloppy2](https://github.com/user-attachments/assets/5489a790-9e1d-4675-a055-8f2f18b47957)
![simplified sloppy 3](https://github.com/user-attachments/assets/a04a890d-0de1-4059-9170-9aaf1eb09493)

What I want is some kind of simplification that can remove or merge topologically separate components, but which doesn't merge vertices on edges, and hence maintains reasonable shading normal fidelity.

Do you have any suggestions for that?  Is it possible with meshoptimizer as-is, or would it need to be added?

Thanks,
  Nick C.

p.s. please feel free to recategorise as a feature enhancement or discussion item.

**Comment by Ono-Sendai** [comment]
Just thinking out loud... what about a pass that computes the topological submeshes, computes bounding boxes of them, and discards any which size below the error threshold?  I think it would help in this case at least.

**Comment by Ono-Sendai** [comment]
> > a pass that computes the topological submeshes, computes bounding boxes of them, and discards any with size below the error threshold
> 
> Yeah this happens to be planned as one of the next improvements to `simplify`.

Oh awesome!   Was thinking of trying it myself.
Presumably there's some code to compute AABBs in there already, i can just adapt it.

**Comment by Ono-Sendai** [comment]
I tried an implementation with some of my code, seems to work well:

It's relatively straightforward, breadth first search over adjacent triangles to identify connected components, compute AABB, compare with error, discard small components.  Runs in linear time on the number of triangles.

I had a look at the meshoptimizer code but the data structures look a little tricky so I think I'll leave that to you :)
Can post my code for reference if you want but I imagine you don't need it.

https://github.com/user-attachments/assets/d4c56282-df12-495e-ae51-2d29096e4c5b

**Comment by zeux** [comment]
If you could share the asset that would be nice; I have a preliminary version of this and would like to make sure it works well on this.

**Comment by Ono-Sendai** [comment]
Here you go: https://www.dropbox.com/scl/fi/7886i6nxgv901mdbqik5y/gallery_exported.glb?rlkey=yck4m16jgw65si45l69yrnc0h&st=acuokyz3&dl=0
