### ISSUE TITLE
gltfpack: UTF-8 encoding of glTF JSON on windows

### ISSUE THREAD

**Issue by kzhsw** [zeux/meshoptimizer#767]
Env: Windows 10 with the [UTF-8 region option](https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do) disabled by default.

Steps to reproduce:
1. get any model with non-ASCII name, e.g. `é.glb`
2. run `gltfpack -i é.glb -o é.gltf`
3. open `é.gltf` in text editor and check its encoding

Actual:
`é.gltf` is not in UTF-8 encoding

Expected:
glTF JSON is encoded in UTF-8 for whatever system encoding

Spec here: <https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#json-encoding>

> glTF JSON data SHOULD be written with UTF-8 encoding without BOM. This requirement is not applied when a glTF implementation does not control string encoding. glTF implementations SHOULD adhere to [RFC 8259](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#json), Section 8.1. with regards to treating BOM presence.

**Comment by zeux** [comment]
Yeah, this needs a fix. Probably sufficient to rely on Windows supporting UTF-8 encoding if requested as a locale, but needs some adjustments to argument handling to avoid having to use a manifest...
