### ISSUE TITLE
gltfpack: support preserving UV sets

### ISSUE THREAD

**Issue by cshenton** [zeux/meshoptimizer#768]
Currently there is (afaict) no option to preserve additional sets of UVs.

I have meshes with separate albedo and lightmap UVs which, due to the lightmapper being external, reference a texture in a separate file. Either way, even when the second UV set references a dummy 1px texture in Blender, gltfpack strips that UV set off and breaks the assets.

Please consider adding a flag to preserve UV sets, similar to the flags to preserve node hierarchy / materials / extras, etc.

**Comment by zeux** [comment]
> when the second UV set references a dummy 1px texture in Blender, gltfpack strips that UV set off and breaks the assets.

This should not be the case. Feel free to provide a reproduction for this. gltfpack will preserve all UV sets that are referenced by textures.

> Please consider adding a flag

If you use the latest pre-release gltfpack (any recent build from https://github.com/zeux/meshoptimizer/actions), you can specify `-kv` to keep unused vertex attributes. Note that for this to work with UV coordinates, you need to additionally specify `-vtf` - by default, gltfpack uses KHR_texture_transform extension to store UV transform required for quantization, and without a texture bound there is nowhere to save this transform.

**Comment by cshenton** [comment]
Sorry to clarify, no reference to a texture exists in the `.glb` file, since blender fails to correctly export such a material despite it being using in the shader explicitly, so gltfpack is working correctly there. I will take a look at using `-kv` with a more recent build.

**Comment by zeux** [comment]
Ah yeah, that makes sense. FWIW the flag was added in https://github.com/zeux/meshoptimizer/pull/719.
