### ISSUE TITLE
MeshoptEncoder.reorderMesh failed.

### ISSUE THREAD

**Issue by RyugaRyuzaki** [zeux/meshoptimizer#785]
I tried to implement MeshoptEncoder.reorderMesh meshoptimizer@0.21.0.  Here is my code 
```
  const index = new Uint32Array([
      0, 1, 2, 2, 3, 0, 4, 5, 6, 5, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
      18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
    ]);
    const [reorderedIndices, uniqueVertexCount] = MeshoptEncoder.reorderMesh(
      index,
      true,
      true
    );
    console.log(reorderedIndices);
    console.log(uniqueVertexCount);
```
The result : 
```
reorderedIndices :Uint32Array length :34 
uniqueVertexCount : 32 
```
    Error: Assertion failed
    at assert (chunk-VZ7CQLHZ.js?v=3a3abf18:31:13)
    at Object.encodeIndexBuffer (chunk-VZ7CQLHZ.js?v=3a3abf18:132:7)
    at MeshoptCompress.compress (index.ts:74:46)
    at async IfcGeometryLoader.streamFromBuffer (IfcGeometryLoader.ts:45:22)
    at async onLoadIfc (StreamedWorker.ts:67:5)
```

**Comment by zeux** [comment]
`MeshoptEncoder.reorderMesh` returns a remap table, not an index buffer. The index buffer is mutated in place. This is clearly documented in https://github.com/zeux/meshoptimizer/tree/master/js#encoder. I assume you feed the remap table into `encodeIndexBuffer`, but that requires 3 indices per triangle.

**Comment by RyugaRyuzaki** [comment]
> `MeshoptEncoder.reorderMesh` returns a remap table, not an index buffer. The index buffer is mutated in place. This is clearly documented in https://github.com/zeux/meshoptimizer/tree/master/js#encoder. I assume you feed the remap table into `encodeIndexBuffer`, but that requires 3 indices per triangle.

Hi, from doc, here my code : 
```
 async compress(
    modelID: number,
    temp: {
      position: Float32Array;
      index: Uint32Array;
    }
  ) {
    const model = this.models.get(modelID);
    if (model === undefined) return;

    await MeshoptEncoder.ready;

    const {position, index} = temp;
    const before = position.byteLength + index.byteLength;

    const [reorderedIndices, uniqueVertexCount] = MeshoptEncoder.reorderMesh(
      index,
      false,
      true
    );
    console.log("oldIndex", index);
    console.log("reorderedIndices", reorderedIndices);
    console.log("uniqueVertexCount", uniqueVertexCount);
    const newVertices = new Float32Array(uniqueVertexCount * 3);

    for (let i = 0; i < index.length; ++i) {
      const oldIndex = index[i];
      const newIndex = reorderedIndices[i];

      newVertices[newIndex * 3] = position[oldIndex * 3]; // x
      newVertices[newIndex * 3 + 1] = position[oldIndex * 3 + 1]; // y
      newVertices[newIndex * 3 + 2] = position[oldIndex * 3 + 2]; // z
    }

    const vertexBuffer = new Uint8Array(newVertices.buffer);
    const compressedVertices = MeshoptEncoder.encodeVertexBuffer(
      vertexBuffer,
      uniqueVertexCount,
      4
    );

    const indexBuffer = new Uint8Array(reorderedIndices.buffer);
    const compressedIndices = MeshoptEncoder.encodeIndexBuffer(
      indexBuffer,
      reorderedIndices.length,
      4
    );

    const totalSize =
      compressedVertices.byteLength + compressedIndices.byteLength;
    const combinedData = new Uint8Array(totalSize);

    combinedData.set(compressedVertices, 0);

    combinedData.set(compressedIndices, compressedVertices.byteLength);
    const after = combinedData.byteLength;
    console.log(`Before compress :${before} bytes`);
    console.log(`After compress :${after} bytes`);
  }
```
And here is result : 
![image](https://github.com/user-attachments/assets/c3133c52-4a6b-443f-929a-41afb9ddeb08)

D=Did i make something wrong? Many thank

**Comment by zeux** [comment]
Yes, this is wrong:

```
    const indexBuffer = new Uint8Array(reorderedIndices.buffer);
```

`MeshoptEncoder.reorderMesh` does not return reordered indices. It returns a remap table. The input array (`indices`) is already reordered after the call, so that is what you should be encoding, not the remap table (which you should only use to reorder all the vertex streams)

**Comment by RyugaRyuzaki** [comment]
> Yes, this is wrong:
> 
> ```
>     const indexBuffer = new Uint8Array(reorderedIndices.buffer);
> ```
> 
> `MeshoptEncoder.reorderMesh` does not return reordered indices. It returns a remap table. The input array (`indices`) is already reordered after the call, so that is what you should be encoding, not the remap table (which you should only use to reorder all the vertex streams)

Hi, but why "4294967295" appears in reorder? What should i do for compress 2 position and index ( 10milions vertices)? Please help me!

**Comment by zeux** [comment]
> why "4294967295" appears in reorder

Oh, the demo code should have a check against this. This happens for unused vertices that got removed during the reordering process; they should be skipped in the vertex adjustment loop.
