### ISSUE TITLE
CMakeLists.txt Add Install Option

### ISSUE THREAD

**Issue by hankarun** [zeux/meshoptimizer#804]
When using meshoptimizer as a part of another project, we don't want it to install with the project. Adding MESHOPTIMIZER_INSTALL as an option which is ON default, can give ability to disable install when ExternalProject and FetchContent_Declare is used.

**Comment by zeux** [comment]
Makes sense, feel free to contribute a PR (should be MESHOPT_INSTALL for consistency)
