### ISSUE TITLE
gltfpack: Animation without resampling

### ISSUE THREAD

**Issue by yannickModulo** [zeux/meshoptimizer#815]
Hi,

We use gltfpack to reduce the number of meshes but we have an unexpected sampling of animation (we use cubic spline). Is it possible to have an option to let untouched the animation without any resampling ?

Best regards

**Comment by zeux** [comment]
It's possible to disable that in theory but requires some extra handling for cubic splines in particular, and maybe some other components of animation serialization need to change to be able to preserve the input data as it was. Out of curiosity, what issues are you running with wrt resampling?

**Comment by yannickModulo** [comment]
two reason : we need to clone at runtime complex and long animation and it takes a lot of time because of the sampling (it will be very fast instead because there is only a few keyframes if there was no sampling). Another reason is to be able to edit the animation in our software : it's totally impossible after sampling.

**Comment by zeux** [comment]
Using `-af 0` with the linked PR should disable animation resampling; I've lightly tested this on assets I have and it appears to work fine, but there may be corner cases I'm not thinking of OTOH. It looks like artifact upload from branches is disabled atm so unless you want to build that branch from source testing would only be possible once it gets merged.

**Comment by yannickModulo** [comment]
Thanks a lot !!!!

**Comment by zeux** [comment]
Binaries with this change should now be available https://github.com/zeux/meshoptimizer/actions/runs/12280430605 (scroll down for artifacts)
