### ISSUE TITLE
Simplification runs, but the result has many defects/issues

### ISSUE THREAD

**Issue by scottmudge** [zeux/meshoptimizer#86]
I am using meshoptimizer's simplification methods to simplify 3D scans w/ have been triangulated using marching cubes. The meshes are far more dense than they need to be, so I am attempting to simplify them down to 20% of their original density.

Unfortunately the result is unusable and full of holes and other defects. Is this normal?

Here is an example:

**Input Mesh**

![image](https://user-images.githubusercontent.com/19617165/70648446-0d3bbb80-1c19-11ea-8379-0a533e00a81a.png)

**Simplified Result**

![image](https://user-images.githubusercontent.com/19617165/70648475-19c01400-1c19-11ea-8b7e-4820d6bb6391.png)

I am using MeshLab to visualize the result. The meshes are exported to STL format.

The mesh format I am using internally in my software is that of the VCG library, but I think I am appropriately converting the data such that meshoptimizer's simplification methods can operate correctly.

Here is how I am converting the data:

```
const MeshVert* __restrict root = input.vert.data();
std::vector<unsigned> remap;
std::vector<vcg::Point3f> vertices;

for (const auto& v : input.vert) 
    vertices.emplace_back(v.P());

for (const auto& f : input.face) {
    remap.emplace_back(unsigned((MeshVert*)(f.cV(0)) - (MeshVert*)root));
    remap.emplace_back(unsigned((MeshVert*)(f.cV(1)) - (MeshVert*)root));
    remap.emplace_back(unsigned((MeshVert*)(f.cV(2)) - (MeshVert*)root));
}

const size_t index_count = remap.size();
std::vector<unsigned> simplified(index_count);
size_t target_count = simplification_factor * index_count;
float target_error = 1e-3f;

if (restricted)
    simplified.resize(meshopt_simplify(&simplified[0], remap.data(), index_count, (const float* __restrict)&vertices[0], vertices.size(), sizeof(vcg::Point3f), target_count, target_error));
else
    simplified.resize(meshopt_simplifySloppy(&simplified[0], remap.data(), index_count, (const float* __restrict)&vertices[0], vertices.size(), sizeof(vcg::Point3f), target_count));
```

I'm a little confused by the concept of "Index" in this mesh processing library. Are the indexes here referring to triplets of offsets from Vertex_Ptr* + 0 which represent each face/triangle?

The VCG mesh has a vector of vertices, each represented by a Point3f type (the internal data of which is 3 floats - X, Y, and Z). The faces contain 3 vertex pointers. I compute the offset/index from these pointers by subtracting the start of the vertex array (root).

Is this the correct approach? Am I doing something wrong? The result looks *reasonable*, but not entirely correct. Perhaps this is just the nature of decimation?

**Comment by scottmudge** [comment]
Just to follow up, I also followed the instructions for creating new index buffers from unindexed/unsorted vertex buffers, but the result looked like noise/garbage.

Here is the code for that:

```
std::vector<vcg::Point3f> unindexed_vertices;

for (const auto& v : input.vert)
	unindexed_vertices.emplace_back(v.P());

const size_t face_count = input.FN();
const size_t vertex_count_input = input.VN();
size_t index_count = face_count * 3;
std::vector<unsigned int> remap(index_count); // allocate temporary memory for the remap table
size_t vertex_count = meshopt_generateVertexRemap(&remap[0], NULL, index_count, &unindexed_vertices[0], vertex_count_input, sizeof(vcg::Point3f));

std::vector<unsigned int> indices(index_count);
std::vector<vcg::Point3f> vertices(vertex_count);
meshopt_remapIndexBuffer(&indices[0], NULL, index_count, &remap[0]);
meshopt_remapVertexBuffer(&vertices[0], &unindexed_vertices[0], vertex_count_input, sizeof(vcg::Point3f), &remap[0]);


std::vector<unsigned> simplified(index_count);
size_t target_count = simplification_factor * index_count;
float target_error = 1e-3f;

if (restricted)
	simplified.resize(meshopt_simplify(&simplified[0], indices.data(), index_count, (const float* __restrict)&vertices[0], vertices.size(), sizeof(vcg::Point3f), target_count, target_error));
else
	simplified.resize(meshopt_simplifySloppy(&simplified[0], indices.data(), index_count, (const float* __restrict)&vertices[0], vertices.size(), sizeof(vcg::Point3f), target_count));
```

I also tried adding in `meshopt_generateShadowIndexBuffer()` with a separate index buffer destination after `meshopt_remapVertexBuffer()`, but that yielded similar garbage results.

**Comment by zeux** [comment]
Holes are unexpected, and imply that the mesh isn't connected - if the original mesh has small holes, simplification may enlarge these holes.

> I'm a little confused by the concept of "Index" in this mesh processing library. Are the indexes here referring to triplets of offsets from Vertex_Ptr* + 0 which represent each face/triangle?

The "index" refers to vertex indices as used in accelerated rendering; each triangle has three indices, that are indices into arrays of vertices. For non-sloppy simplifier, it's expected that the vertices are deduplicated (equivalent vertices occur just once in the vertex array); for sloppy simplifier it doesn't matter.

The simplified result is what I'd generally expect from non-sloppy simplifier, modulo holes.

I'll need to carefully read the code snippets later to see if anything else might be going on here. Can you show how `input` is defined in your code with associated structures?

**Comment by scottmudge** [comment]
Interesting, thank you for that feedback. 

The input mesh should have all close/near vertices merged together (de-duplicated), but I see similar holes and sporadic inverted faces/normals with both the sloppy and un-sloppy simplification methods as well.

The input mesh is of a `vcg::tri::TriMesh<...>` type, and so it is a bit complex. But it follows the structure defined here:

http://vcg.isti.cnr.it/vcglib/basic_concepts.html

I believe the structure of the face vector is similar to GPU index buffers. Each face contains three pointers (from which an array index can be computed), each pointing to the vertex the face is represented by. So I simply populate an index buffer by computing the array offsets from these pointers.

Perhaps the input mesh isn't quite ideal? I can try inputting a known good mesh to see if that works well and that the translations from the vcg Mesh to one meshoptimizer understands is working correctly. Do you have a good benchmark mesh that you know decimates well?

**Comment by zeux** [comment]
I don’t see any obvious issues in the first code snippet you posted. It seems correct to me. It would be more comfortable to add a static assertion that Point3f has a sizeof of 12 because you are reinterpreting the bits as float starting from offset 0, just to make sure there’s no vtable in that object.

Your second code snippet should not work because it is ignoring the input face data so you synthesize a different index order. But actually after thinking about this, I would not expect base simplifier to produce holes given redundancy in vertex data, it is specifically engineered to guard against this.

So I must be missing something. Would it be possible to get the mesh you are having issues with as an .obj file?

The simplifier is usually tested on a variety of high polygon models from various sources; one example of classical position only models in the polygon range you are looking at are Happy Buddha. (I have a large data set but I am not sure what the licensing is on individual models wrt sharing them)

**Comment by zeux** [comment]
Oh and the simplified results with baseline simplifier can occasionally contain flipped triangles due to how vertices travel around the mesh. I don’t think sloppy simplifier can produce them, and it didn’t come up as a severe issue in prior testing but maybe your data exacerbates this somehow...

**Comment by scottmudge** [comment]
Sure, I can supply you a sample file.

It is indeed quite mysterious. The sample file provided here has highly curved and highly planar regions. The highly curved regions seemed to not be simplified quite as much with the non-sloppy version, and so had fewer holes and defects, but the highly planar regions in both the sloppy and non-sloppy simplification methods had many holes and other defects. I see flipped triangles in both sloppy and non-sloppy processing. 

See below:

**Unprocessed**

![image](https://user-images.githubusercontent.com/19617165/70717572-9eb03980-1cbc-11ea-991a-4badc59a3456.png)

**Regular/Non-Sloppy**

![image](https://user-images.githubusercontent.com/19617165/70717609-b091dc80-1cbc-11ea-9dc9-f89d8f5f4d4a.png)

**Sloppy**

![image](https://user-images.githubusercontent.com/19617165/70717635-bc7d9e80-1cbc-11ea-8c4a-36ddf52ff945.png)

Attached are the OBJ files. There are three -- 1 unprocessed, 1 processed @ 20% decimation factor w/ sloppy, and 1 processed @ 20% decimation factor w/ non-sloppy/regular simplification.

Any insight would be greatly appreciated. Thanks again for the insight.

**Files:**

[test_obj_files.zip](https://github.com/zeux/meshoptimizer/files/3956007/test_obj_files.zip)

**Comment by scottmudge** [comment]
Is it possible to give it a mutable float/vertex buffer and modify the simplification algorithm such that it moves the vertices to their correct location such that the holes and other defects are corrected? I suppose if these defects are abnormal it wouldn't help... since the algorithm must think the result is correct.

I also tried changing:

```
for (const auto& v : input.vert)
		vertices.emplace_back(v.P());

for (const auto& f : input.face) {
		remap.emplace_back(unsigned((MeshVert*)(f.cV(0)) - (MeshVert*)root));
		remap.emplace_back(unsigned((MeshVert*)(f.cV(1)) - (MeshVert*)root));
		remap.emplace_back(unsigned((MeshVert*)(f.cV(2)) - (MeshVert*)root));
}
```

to:

```
vertices.resize(input.FN() * 3);
for (const auto& f : input.face) {
	register MeshVert* __restrict const v1 = (MeshVert*)(f.cV(0));
	register MeshVert* __restrict const v2 = (MeshVert*)(f.cV(1));
	register MeshVert* __restrict const v3 = (MeshVert*)(f.cV(2));
	const unsigned v1_idx = (v1 - root);
	const unsigned v2_idx = (v2 - root);
	const unsigned v3_idx = (v3 - root);

	vertices[v1_idx] = v1->cP();
	vertices[v2_idx] = v2->cP();
	vertices[v3_idx] = v3->cP();

	if (!f.IsD()) {
		remap.emplace_back(v1_idx);
		remap.emplace_back(v2_idx);
		remap.emplace_back(v3_idx);
	}
}
```

In order to ensure the index buffer exactly matches what the face vector thinks is correct, but the result is the same.

**Comment by zeux** [comment]
So the good news is that you *are* getting a substantially different result compared to what I am getting on this mesh.

I've used lodviewer (you can build it yourself if you want, `tools/lodviewer.cpp` - just add this file and all of the files in `src` folder to a Visual Studio project if that's what you use, but you'll also need to install glfw - I do it through NuGet; this is an internal test application I use to develop meshoptimizer's simplifier) to simplify this mesh (keys 1-9; I used 2), check it's wireframe (W), export it to a file (S) and open it in MeshLab:

![image](https://user-images.githubusercontent.com/1106629/70870062-d7ae0f80-1f43-11ea-93e1-e71428171ea7.png)

Compared to that, your simplified result indeed looks much different:

![image](https://user-images.githubusercontent.com/1106629/70870093-35425c00-1f44-11ea-9657-f43087c46a69.png)

I'm not sure I know why that is. Clearly there's some difference in processing on your side but I don't understand what that might be yet. I was initially worried that your mesh has some sort of defective topology, but lodviewer has debug settings to let me explore that and it looks very clean:

![image](https://user-images.githubusercontent.com/1106629/70870119-5c992900-1f44-11ea-88d9-bbc34fd02abf.png)

Consequently the non-sloppy simplifier has no problems simplifying this mesh pretty much arbitrarily:

![image](https://user-images.githubusercontent.com/1106629/70870128-6fabf900-1f44-11ea-83b3-28e3dcdf9ba2.png)

With minimal topology issues:

![image](https://user-images.githubusercontent.com/1106629/70870131-76d30700-1f44-11ea-867f-9475d99eac51.png)

About the only issue I see in MeshLab on moderate tessellation is the self-intersecting faces for non-sloppy; sloppy simplifier shouldn't encounter that. Non-sloppy simplifier doesn't currently guard against that; this isn't on my TODO list atm but could be.

Regardless, something is different in your application. Would it be possible to share more code, specifically what you do with the simplified result?

Quick point of note: the simplifier is sensitive to the face winding order. It's not clear to me from your code whether the faces have consistent winding or not, the .obj file you uploaded does have consistent winding so I'm just mentioning this on the off chance there's some difference there.

And just want to confirm again that sizeof(vcg::Point3f) is 12? When I looked at this earlier, depending on the configuration Point3f is either a simple VCG struct or a wrapper around Eigen's Vector3 and I don't know Eigen enough to understand if that data layout is also simply 3 floats with no extra data before it.

**Comment by zeux** [comment]
... oh, actually, I take this back. I noticed that the input .obj file doesn't have normals but the output file from lodviewer has dummy normals. When I reexported with no normals, letting MeshLab generate them, I get this:

![image](https://user-images.githubusercontent.com/1106629/70870300-64f26380-1f46-11ea-94ea-3b165df88ab4.png)

There are *no* holes in this mesh, unlike yours, but the normals are all over the place, presumably because of triangle flips. This ceases to be a problem for more aggressive simplification:

![image](https://user-images.githubusercontent.com/1106629/70870314-99feb600-1f46-11ea-9281-4061e130cdb4.png)

So I guess there are two issues here:

- On moderate simplification ratios, simplifier creates overlapping faces, which causes MeshLab to generate incoherent normals. This is not ideal, I need to think about how I can block the vertex movement to prevent this without losing too much performance.

- There are still no holes in my results (the point I was originally very confused about), so there's some discrepancy in the code's behavior between your application and mine.

Sloppy simplifier also produces overlapping triangles occasionally but that's going to probably be impossible to rectify:

![image](https://user-images.githubusercontent.com/1106629/70870363-4476d900-1f47-11ea-95ab-67c0f47a8d9d.png)

I also suspect that MeshLab generates normals (in their absence) by simply averaging triangle normals across all triangles that adjoin the vertex; this will naturally produce shading issues like in the screenshots above, the normal generation algorithms I'm more used to for production use tend to split vertices on normal discontinuities, which would make the issue here much less pronounced. Not sure what your target application needs to do with this data.

**Comment by scottmudge** [comment]
Hello,

Thank you for that very thorough reply. I'm currently on my mobile, but I will compile lodviewer tomorrow and dig into this further. I suspect there is something going on, perhaps with the normals as you noted. I am using the same core library Meshlab uses (VCG) so if it produces errors in its normal estimation, then that may be my problem.

I will also compare my mesh initialization code to that used in lodviewer to make sure the data is properly structured before being simplified. I did statically assert that vcg::Pount3f is 12 bytes, which it is, but I'm wondering if there is some weird  behavior where the x y and z coordinates aren't always indexed the same way. I will copy the data directly into a float array to make sure it is.

I'll follow up again tomorrow and let you know what I discover. Thanks again for the thorough and well thought support!

**Comment by lihongyi1234** [comment]
Hello,
    I have counter the same question ,when use the function of  meshopt_simplify, I have no idle what to do,so would you please tell me what you discovering after you using lodviewer , I am looking forward to you reply, thank  you!!!
<img width="664" alt="微信图片_20200211223039" src="https://user-images.githubusercontent.com/36233282/74245572-2dbdea00-4d1e-11ea-83db-8d41aa4a27b0.png">

**Comment by lihongyi1234** [comment]
added!!the initial .obj file contains about  100000 faces,the samplified .obj file contains about 60000 faces that I set the threadshold equal to 0.6.

**Comment by zeux** [comment]
@lihongyi1234 Fixing this requires changing the simplifier to restrict vertex movement in order to avoid creating overlapping triangles. I haven't had time to look into solving this yet; for now you could try to increase the decimation level to avoid this, as it seems to mostly happen on moderate ratios.

**Comment by lihongyi1234** [comment]
@zeux Thanks for your prompt repley, would you please share your .obj file which you tested corrected 
because I don't know if there is something wrong with my procedures. Of course ,I can also share my .obj file too. Looking forward to your letter and thanks again!

**Comment by lihongyi1234** [comment]
added!!!there is my initial .obj file
[test.zip](https://github.com/zeux/meshoptimizer/files/4189742/test.zip)

**Comment by oschakravarthi** [comment]
Hi @zeux 
I have explored so many mesh simplifiers but yours is the best. Thanks a lot for such dimple yet powerful component. 
Please try to fix this issue. With this fix, it will be a complete solution and production ready. 

> @lihongyi1234 Fixing this requires changing the simplifier to restrict vertex movement in order to avoid creating overlapping triangles. I haven't had time to look into solving this yet; for now you could try to increase the decimation level to avoid this, as it seems to mostly happen on moderate ratios.

**Comment by EvilTrev** [comment]
Bump. This is a show stopping issue for me too. Meshes that fold, reverse faces and overlap randomly create issues for the rest of our pipeline when it comes to blends, skirts and visibility culling solutions. It would be nice if there was a simplification routine that (even if slower) could ensure these conditions are avoided. Thanks!
