### ISSUE TITLE
Defective LOD generation for Lumberyard Bistro

### ISSUE THREAD

**Issue by corporateshark** [zeux/meshoptimizer#88]
*Preparing:*

Download Bistro from http://casual-effects.com/data/index.html

*Running:*

`lodviewer.exe bistro/Exterior/exterior.obj`

*Observing:*

Damaged texture coordinates. Multiple holes in the mesh.

![image](https://user-images.githubusercontent.com/2510143/71030055-b99e0600-2121-11ea-977d-25e4a3598588.png)

![image](https://user-images.githubusercontent.com/2510143/71030072-c3276e00-2121-11ea-84a3-81b65335bd67.png)

**Comment by donmccurdy** [comment]
I think I'm seeing a similar issue in v0.13 of gltfpack. Testing against the model here: https://sketchfab.com/3d-models/melodia-city-hotel-a2fb8e4065ce470296d6d801daa37f18, with only default gltfpack options used:

| before | after |
|---|---|
|  ![before](https://user-images.githubusercontent.com/1848368/71429444-81e01280-267b-11ea-8513-7a20e5aaab85.png) | ![after](https://user-images.githubusercontent.com/1848368/71429445-83113f80-267b-11ea-96a3-019076cc0d07.png) |

annotated diff:

![diff](https://user-images.githubusercontent.com/1848368/71429490-b18f1a80-267b-11ea-89a5-df9ec7c0076e.png)

^Much of that diff is in reflections, which probably relates to merging meshes with transparency, and that seems fine. But the highlighted areas on the side of the building and the palm trees in front of the building show noticeable UV shifts that might suggest an issue?

**Comment by zeux** [comment]
This is a separate issue - by default gltfpack doesn’t simplify. I think this is related to some long standing quality improvements that need to happen for meshes with a high tiling rate. Would you mind opening a separate issue? On vacation atm with limited time so I will probably only get to this in January.

**Comment by donmccurdy** [comment]
@zeux Done, and opened https://github.com/zeux/meshoptimizer/issues/93. No rush on this, just wanted to report it while I remembered. Enjoy the vacation!

**Comment by corporateshark** [comment]
This is still not fixed in the most recent version d0d1c2ad04886c3d99bb5e3f20d6cf872676f02c. Both UVs and normal vectors are broken starting from LOD 1.
