### ISSUE TITLE
Unprefixed CMake options polluting global namespace

### ISSUE THREAD

**Issue by corporateshark** [zeux/meshoptimizer#90]
MeshOptimizer uses generic unprefixed names for its CMake options. For example:
```
option(BUILD_DEMO "Build demo" OFF)
option(BUILD_TOOLS "Build tools" OFF)
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
```

There's no problem if MeshOptimizer is compiled as a standalone project. 

However, when MeshOptimizer is compiled as a part of a complex CMake build process, these option names do pollute the global namespace.

Popular libraries use prefixes for their CMake options. For example, `Assimp` uses the `ASSIMP_` prefix (`ASSIMP_BUILD_ASSIMP_TOOLS`, `ASSIMP_BUILD_ASSIMP_TESTS`, etc), and `GLFW` uses the `GLFW_` prefix (`GLFW_BUILD_EXAMPLES`, `GLFW_BUILD_DOCS`, etc).

Similar approach should be adopted for MeshOptimizer.

**Comment by zeux** [comment]
This seems reasonable. We can probably use MESHOPT_ prefix for this.
