### ISSUE TITLE
Consider adding a --version flag

### ISSUE THREAD

**Issue by donmccurdy** [zeux/meshoptimizer#92]
Before commenting on #88 I'd wanted to make sure I had the latest version of gltfpack, and wasn't able to tell from inspecting the executable or its CLI output. A `gltfpack --version` flag would be helpful for that purpose. Thanks!

**Comment by zeux** [comment]
gltfpack uses single-letter options; I thought this would be `-v` but of course that already means "verbose" 😅 I might need to change that, or maybe just use `gltfpack -v` as a way to output the version when no other command line arguments are present.

**Comment by donmccurdy** [comment]
Currently `gltfpack -v` prints the full help output anyway, maybe just show the version number somewhere in that text? FWIW here's my usage output for `gltf-transform`, built with [caporal](https://www.npmjs.com/package/caporal):

![Screen Shot 2019-12-25 at 11 40 37 AM](https://user-images.githubusercontent.com/1848368/71449847-67ee1080-270b-11ea-9741-e528f3884c53.png)

**Comment by donmccurdy** [comment]
Thanks!
