### ISSUE TITLE
Different vertex count between tiny obj loader and fast obj loader

### ISSUE THREAD

**Issue by giordi91** [zeux/meshoptimizer#94]
Good afternoon, hope you are having a nice xmas break. 

I have been using fast obj for my vulkan code and worked quite well. Now I need to merge back into my main engine, where I have a mesh compiler which uses tiny obj loader, when I ported the code to fast obj I started noticing this issue, in loading the file I am getting an extra vertex from fast obj.
Tiny obj: 3792
Fast obj: 3793

Maya reports 3792:
![image](https://user-images.githubusercontent.com/2525797/71545199-3e89ea80-2980-11ea-8c7c-f6ad6ff660b5.png)

This is an issue on my end because I am exporting extra data from Maya, like tangents and skinning data, of which I use the same obj indexing to fetch. Having the extra array I get an out of bound assertion. 

Here below (and attached) a sample code to reproduce:
```c++
#define TINYOBJLOADER_IMPLEMENTATION
#include "tiny_obj_loader.h"

#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#define FAST_OBJ_IMPLEMENTATION
#include "fast_obj.h"

#include <iostream>

const char *PATH = "test.obj";

int main() {
  // loading the obj using tiny
  tinyobj::attrib_t attr;
  std::vector<tinyobj::shape_t> shapes;
  std::vector<tinyobj::material_t> materials;

  std::string warn;
  std::string err;
  bool ret = tinyobj::LoadObj(&attr, &shapes, &materials, &warn, &err, PATH);
  if (!ret) {
    printf("Error loading %s: file not found\n", PATH);
    return 0;
  }

  //loading using fast obj
  fastObjMesh *obj = fast_obj_read(PATH);
  if (!obj) {
    printf("Error loading %s: file not found\n", PATH);
    return false;
  }

  //now compare
  printf ("Tiny vertex count %i \n" ,static_cast<int>(attr.vertices.size()/3));
  printf ("Fast vertex count %i" ,obj->position_count);
}
```

Here the output:
![image](https://user-images.githubusercontent.com/2525797/71545280-501fc200-2981-11ea-8db0-f47e3433afe1.png)

Am I doing anything wrong? I have thought on what the issue could be and did not find a solution yet. I have also tried per-triangulating the mesh before export, and got the same result. 
If anything else is needed on my side please let me know. 

The main reasons I am switching to fast obj is:
1) hopefully faster debug and release performance then tiny.
2) Since I am about to use mesh optimizer anyway I can just use fast obj and have one dependency, not two.

Best regards

M.

solution/code/model link: https://1drv.ms/u/s!Ai0n7iKmKMz0gthD0wT4C3KUKbW5Pw?e=eKo2ZN

**Comment by zeux** [comment]
Note: fast_obj is https://github.com/thisistherk/fast_obj; it’s technically not part of meshoptimizer, it’s just used for demo & tools.

The indices in fast_obj are 1-based, with 0 reserved for dummy attribute values. Because of this there’s one extra position/normal/texture coordinate.

This isn’t very necessary for positions as they must always be present, I think it’s implemented that way for consistency. It’s important for normals and texture coordinates as they can be missing from arbitrary faces.

**Comment by giordi91** [comment]
Thank you I was writing this meanwhile you replied. I did find the extra dummy attribute both in the code and in the data.

Apologies I thought it was your own code. apologies for that. Thank you for your fast reply. I will deal with this on my side. thank you.
