### ISSUE TITLE
Encode/decode vertex deinterleaved

### ISSUE THREAD

**Issue by jtorresfabra** [zeux/meshoptimizer#99]
Hi @zeux,

Maybe I'm getting it wrong, but if I want to encode/decode deinterleaved vertex arrays it seems that I'm forced to use always multiple of 4 bytes per vertex attribute:

https://github.com/zeux/meshoptimizer/blob/master/src/vertexcodec.cpp#L1070

For instance, it means that I would need to use floats instead of shorts for quantized positions. That probably is not an issue when encoding, as general compressors are going to deflate this unused space for each float.
 
The problem comes for me when decoding, I usually upload quantized attributes to the graphics card and dequantize them in the shader (normals, positions, etc). If I use meshoptimizer decode, will l be spending extra memory in the GPU if I upload the buffer directly from decode? I guess yes. In that case I would need to think if it's better to spend the extra time on copying arrays or spend the extra memory in GPU. 

Is what I said correct? Any advice on the matter?

Thanks!

**Comment by zeux** [comment]
> For instance, it means that I would need to use floats instead of shorts for quantized positions

The vertex data currently needs to be aligned to 4 bytes, but individual components don't. For example, when encoding deinterleaved data, you'd need to encode quantized positions using 8 bytes per attribute, not 6 bytes.

Not all graphics APIs support streams that aren't 4 byte aligned, what APIs are you targeting? It's probably possible to lift this restriction as it only applies to SIMD decoder, but I'm not sure what the usecase is.

**Comment by jtorresfabra** [comment]
Ummm for now we target WebGL/OpenGL, and I was uploading to the graphics card uint16 vec3 attribute arrays for positions, and dequantize in the shader, the same for normals (uint8 vec2 attribute arrays) or tex coords.

Now if I don't want to do an extra step I need to upload int32 vec3 arrays. Maybe the driver was doing the magic for me and converting to 4byte aligned?

Not sure I explained myself very well, but will try to have a look at vram memory in the graphics card.

**Comment by zeux** [comment]
> Now if I don't want to do an extra step I need to upload int32 vec3 arrays for positions, int32 vec2 arrays for normals, etc.

You only need to align the attribute itself to 4 bytes. So you can use uint16 vec4 array for positions, and uint8 vec4 array for normals.

Somehow I thought that WebGL requires 4 byte aligned data and this is where the matching glTF restriction comes from, but maybe that's not the case. I'd need to look into what it would take to make it possible to decode unaligned data.

**Comment by jtorresfabra** [comment]
>You only need to align the attribute itself to 4 bytes. So you can use uint16 vec4 array for positions, and uint8 vec4 array for normals. 

Yep ok, I can save some space this way. Thanks for the pointer.

**Comment by Jiboo** [comment]
For Vulkan, in a VkVertexInputAttributeDescription, "format must be allowed as a vertex buffer format, as specified by the VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT flag in VkFormatProperties::bufferFeatures returned by vkGetPhysicalDeviceFormatProperties".

The spec doesn't force this flag on R8G8B8_* or R16B16G16_* to be mandatory, the hardware database says thus formats are availablle to 66.1% (seems like only AMD does not support thus).
